var annotated_dup =
[
    [ "AnimationSequence", "struct_animation_sequence.html", "struct_animation_sequence" ],
    [ "Background", "class_background.html", "class_background" ],
    [ "Character", "class_character.html", "class_character" ],
    [ "Collision", "class_collision.html", "class_collision" ],
    [ "CollisionBoxes", "struct_collision_boxes.html", "struct_collision_boxes" ],
    [ "CollisionSides", "struct_collision_sides.html", "struct_collision_sides" ],
    [ "EntityBase", "class_entity_base.html", "class_entity_base" ],
    [ "EventManager", "class_event_manager.html", "class_event_manager" ],
    [ "EventTriggeredObject", "class_event_triggered_object.html", "class_event_triggered_object" ],
    [ "Factory", "class_factory.html", "class_factory" ],
    [ "Finish", "class_finish.html", "class_finish" ],
    [ "GameManager", "class_game_manager.html", "class_game_manager" ],
    [ "HUD", "class_h_u_d.html", "class_h_u_d" ],
    [ "LevelObject", "class_level_object.html", "class_level_object" ],
    [ "MoveablePlatform", "class_moveable_platform.html", "class_moveable_platform" ],
    [ "NPC", "class_n_p_c.html", "class_n_p_c" ],
    [ "Platform", "class_platform.html", "class_platform" ],
    [ "Player", "class_player.html", "class_player" ],
    [ "Projectile", "class_projectile.html", "class_projectile" ],
    [ "Screen", "struct_screen.html", "struct_screen" ],
    [ "SettingsData", "struct_settings_data.html", "struct_settings_data" ],
    [ "SoundPlayer", "class_sound_player.html", "class_sound_player" ],
    [ "Spikes", "class_spikes.html", "class_spikes" ],
    [ "Text", "class_text.html", "class_text" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "Timers", "class_timers.html", "class_timers" ],
    [ "ViewInfo", "struct_view_info.html", "struct_view_info" ],
    [ "ViewManager", "class_view_manager.html", "class_view_manager" ]
];