V2THGA group 1 (MiNd_F*cK): NPC Class Reference
NPC Class Reference
This is the NPC class.
#include <NPC.hpp>
Public Member Functions
NPC (const sf::Vector2f &startPoint, const float &deltaXMovement, int screenNumber, const uint_least8_t &health, const uint_least8_t &damage, bool jumpingEnabled=false, const sf::Time &jumpDeltaTime=sf::seconds(0))
This is the constructor for the NPC class.
virtual ~NPC ()
virtual void bindActions () override
This method is should be overridden if you want to bind multiple actions at once.
virtual void bindAnimations () override
This method should be overridden if you want to bind multiple animations at once.
virtual void handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) override
This method handles the collision for a Character.
virtual void handleNoCollision () override
This method handles a no collision.
virtual void hurt (uint_least8_t damage) override
This is a virtual method should be overridden if you want to hurt a EntityBase on damage.
virtual void update (const sf::Time &deltaTime) override
This method updates all the values in the Character.
Public Member Functions inherited from Character
Character (const sf::Vector2f &position, const sf::Vector2f &size, int screenNumber, const sf::Vector2f &maxVelocity, const sf::Vector2f &acceleration, const std::string &characterSheetPath)
This is the constructor of the Character class.
virtual ~Character () override
void addAction (const Action &newAction)
This method adds a new action to mUnperformedActions.
void bindAction (const EventManager &event)
This method binds an event to an action.
void bindAnimation (const State &state, const AnimationSequence &animationSequence)
This method binds a state to an AnimationSequence.
void move (sf::Vector2f &delta)
This method moves the Character.
void applyMovement (const Action &direction)
This method is used to apply the right movement given an action using the velocity.
void updateFacingDirection ()
This method updates the facing direction.
void updateVelocity (const sf::Vector2f &deltaVelocity)
This method adds a given delta velocity to the current mVelocity.
void resetVelocityY ()
This method sets the Y direction of mVelocity to 0.
void resetVelocityX ()
This method sets the X direction of mVelocity to 0.
bool isMovingX () const
This method checks whether the Character is moving in the X direction.
void updateState (const Action &action)
This function updates the current state of the Character.
void startHurtAnimation ()
This method starts the hurting animation.
void animate (const sf::Time &deltaTime)
This method is used to animate the Character his movement.
void left ()
This method moves the Character to the left using applyMovement.
void right ()
This method moves the Character to the right using applyMovement.
void jump ()
This method makes the Character jump into the air.
void run ()
This method makes the Character run using applyMovement.
virtual bool shoot ()
This method is used to shoot a projectile.
virtual bool isShooting () const
This method returns the value of mIsShooting.
std::optional< std::unique_ptr< EntityBase > > getProjectile ()
This method returns a projectile when the Character is shooting.
void performAction (const Action &unperformedAction)
This method performs the given action.
virtual sf::Vector2f getSize () const override
This method returns the size of the Character.
virtual sf::FloatRect getGlobalBounds () const override
This method returns the global bounds of the Character.
void setSpriteScale (float x, float y)
This method sets the scale of mSprite and updates mSize accordingly.
void updateSizeUsingSprite ()
This method updates mSize using the global bounds of mSprite.
virtual bool isFinished () const override
This method returns the value of mIsFinished.
virtual void draw (sf::RenderWindow &window) override
This method draws the Character to a sf::RenderWindow.
virtual void draw (ViewManager &window) override
This method draws the Character to a ViewManager.
Public Member Functions inherited from EntityBase
EntityBase (const sf::Vector2f &position, const sf::Vector2f size, int screenNumber, bool isSolid=true, bool isVisible=true)
This is the constructor for the EntityBase class.
virtual ~EntityBase ()
uint_least64_t getId () const
A method to get the id.
void move (float deltaX, float deltaY)
This method moves the EntityBase by adding the delta to mPosition.
void move (const sf::Vector2f &deltaPosition)
This method moves the EntityBase by adding the delta to mPosition.
void setScreenNumber (int newScreenNumber)
This method sets the screenNumber.
int getScreenNumber () const
This method returns the value of mScreenNumber.
void setIsVisible (bool isVisible)
This method sets mIsVisible.
bool isVisible () const
This method returns mScreenNumber.
void setIsSolid (bool isSolid)
This method sets mIsSolid.
bool isSolid () const
This method returns the value of mIsSolid.
void destroy ()
This method sets mShouldDestroy to true.
bool shouldDestroy () const
This method returns mIsSolid.
void setPosition (float x, float y)
This method sets mPosition.
virtual void setPosition (const sf::Vector2f &newPosition)
This method sets mPosition.
void setSize (const sf::Vector2f &newSize)
This method sets mSize.
virtual sf::Vector2f getPosition () const
This method returns the value of mPosition.
virtual sf::Vector2f getNextPosition () const
This method returns the next position the EntityBase will be.
void removeNonSolid (std::vector< std::unique_ptr< EntityBase > *> &top, std::vector< std::unique_ptr< EntityBase > *> &bottom, std::vector< std::unique_ptr< EntityBase > *> &left, std::vector< std::unique_ptr< EntityBase > *> &right, CollisionSides &hitSides) const
This method removes the non solid objects from the vector.
virtual void setColor (const sf::Color &newColor)
This method handles changing color if overridden.
void drawIfVisible (sf::RenderWindow &window)
This method draws to the sf::RenderWindow if mIsVisible is true.
void drawIfVisible (ViewManager &window)
This method draws to the ViewManager if mIsVisible is true.
Private Attributes
sf::Vector2f mStartPoint
This is the position where the NPC will spawn at.
float mDeltaXMovement
This is the amount of difference in the X axis the NPC will walk from mStartPoint.
bool mIsMovingRight
The NPC is moving to the right if this is true.
The NPC is moving to the left if this is false.
sf::Time unableToMoveTime = sf::seconds(2)
The amount of time the NPC is unable to move after a collision.
Timer unableToMoveTimer
This is a timer used to make the player unable to move for a given time.
bool mJumpingEnabled
The NPC is able to jump if this is true.
The NPC is NOT able to jump if this is false.
sf::Time mJumpDeltaTime
This is the time there should be between jumps.
sf::Clock lastTimeSinceJumpClock
This clock is used to check how long it has been the NPC jumped for the last time.
bool mAbleToMove
The NPC is able to move if this is true.
The NPC is NOT able to move if this is false.
uint_least8_t mHealth
This is the amount of health the player got at the moment.
uint_least8_t mDamage
This is the amount of damage the NPC will deal when something hit him.
Timers hitClocks
These are all the clocked objects which are hurt by the NPC.
Additional Inherited Members
Public Types inherited from Character
enum State {
State::Idle, State::Moving, State::Running, State::Jumping,
State::Falling, State::Shooting
}
enum Action {
Action::Left, Action::Right, Action::Jump, Action::Run,
Action::Shoot, Action::None
}
The actions which a Character is able to perform.
Static Public Member Functions inherited from EntityBase
static void backToStartId ()
Set the nextId to zero. (Reset)
Protected Attributes inherited from Character
uint_least64_t id
The id of a Character used to identify which Character it is.
sf::Vector2f mVelocity
The current velocity of the Character used to move the Character.
sf::Vector2f mMaxVelocity
The mamixum velocity of the Character. The Character is not able to exceed this velocity.
sf::Vector2f mAcceleration
The amount of acceleration of the Character.
bool mIsFacingRight
The Character is facing right if this is true.
The Character is facing left if this is false.
bool mIsInAir
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mIsJumping
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mCanDoubleJump
The Character is in the air if this is true.
The Character is not on the ground if this is false.
bool mIsRunning
The Character is running if this is true.
The Character is not running if this is false.
bool mIsShooting
The Character is shooting if this is true.
The Character is not shooting if this is false.
bool mIsFinished
The Character is finished if this is true.
The Character is not finished if this is false.
State mPreviousState
The previous state the Character was in.
State mState
The current state the character is in.
sf::Texture mTexture
The texture of the Character.
sf::Sprite mSprite
The sprite of the Character.
bool mIsHurting = false
The Character is hurting if this is true.
The Character is not hurting if this is false.
CollisionSides mRestrictedSides
The direction in which the character can not walk.
float mGravity = 0.0f
The amount of pixels the character moves down each update.
This only occurs if the character is in air.
float mStartingJumpForce = -7.0f
The amount of pixels the character moves up when the jump starts.
float mJumpForce = mStartingJumpForce
The amount of pixels the character moves up each update.
This only occurs if the character is jumping.
float mMaxGravity = 7.0f
The maximum amount of pixels the character moves down each update.
float mJumpAcceleration = 0.3f
The amount of pixels the mJumpForce is decreased by each update.
float mGravityAcceleration = 0.3f
The amount of pixels the mGravity is increased by each update.
Timer mShootTimer
The timer to stop the Character from shooting continuously.
sf::Time mTimeBetweenShots = sf::seconds(1)
The time there is between shots.
sf::Time mTimeSinceLastAnimation
The last time a new picture has been set during a AnimationSequence.
Timer mHurtTimer
The timer used to check if the hurt animation should stop.
sf::Time mTotalHurtTime = sf::seconds(1)
The time the hurt animation is shown.
std::queue< Action > mUnperformedActions = {}
All the unperformed actions. These will be performed in the update method.
sf::Vector2i currentSprite = sf::Vector2i(0,0)
The current location in the spritesheet.
std::vector< std::pair< Action, std::function< void()> > > mActions
These are all the possible actions which can be performed.
std::vector< std::pair< State, AnimationSequence > > mAnimations = {}
These are all the states which should be filled in any derived class.
std::vector< EventManager > actions = {}
These are all the events/actions the Character has.
Protected Attributes inherited from EntityBase
uint_least64_t id
The id of the EntityBase.
sf::Vector2f mPosition
The position of the EntityBase in the world.
sf::Vector2f mSize
The size of the EntityBase.
int mScreenNumber
The screen the EntityBase should be drawn to.
bool mIsVisible
The EntityBase is visible on the screen if this is true.
The EntityBase is NOT visible on the screen if this is false.
.
bool mIsSolid
The EntityBase is solid on the screen if this is true.
The EntityBase is NOT solid on the screen if this is false.
.
bool mShouldDestroyed
The EntityBase should be destroyed if this is true.
The EntityBase should NOT be destroyed if this is false.
.
Static Protected Attributes inherited from EntityBase
static uint_least64_t nextId = 0
The first id which is free to use for a new EntityBase object.
Detailed Description
This is the NPC class.
This class is used to make non playable characters a the game. These non playable characters move through the levels using a small algorithm.
Definition at line 15 of file NPC.hpp.
Constructor & Destructor Documentation
NPC()
NPC::NPC (const sf::Vector2f & startPoint, const float & deltaXMovement, int screenNumber, const uint_least8_t & health, const uint_least8_t & damage, bool jumpingEnabled = false, const sf::Time & jumpDeltaTime = sf::seconds(0))
This is the constructor for the NPC class.
Parameters
startPoint The position where the player spawns at.
deltaXMovement The amount of difference in the X axis the NPC will walk from mStartPoint.
screenNumber The screen you want to draw the NPC to.
health The health for a NPC.
damage The damage the NPC will deal to other objects.
jumpingEnabled Whether or not jumping is enabled.
jumpDeltaTime The time there should be between jumps.
Definition at line 3 of file NPC.cpp.
References bindActions(), bindAnimations(), mIsMovingRight, and Character::setSpriteScale().
~NPC()
NPC::~NPC () virtual
Definition at line 36 of file NPC.cpp.
Member Function Documentation
bindActions()
void NPC::bindActions () override virtual
This method is should be overridden if you want to bind multiple actions at once.
This method is called on construction.
Reimplemented from Character.
Definition at line 38 of file NPC.cpp.
References Character::addAction(), Character::bindAction(), Character::Jump, lastTimeSinceJumpClock, Character::Left, mAbleToMove, mDeltaXMovement, mIsMovingRight, mJumpDeltaTime, mJumpingEnabled, and Character::Right.
bindAnimations()
void NPC::bindAnimations () override virtual
This method should be overridden if you want to bind multiple animations at once.
This method is called on construction.
Reimplemented from Character.
Definition at line 62 of file NPC.cpp.
References Character::bindAnimation(), Character::Idle, and Character::Moving.
handleCollision()
void NPC::handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) override virtual
This method handles the collision for a Character.
This method is called by the Collision class. In this method the restrictedSides is updated, mIsInAir is set to false when the Character hits the ground, the position is set correctly when standing on a moving object, etc. If you want a more in depth view of what's happening in this method. You should check the defintion.
Reimplemented from Character.
Definition at line 83 of file NPC.cpp.
References Timers::addTimer(), Character::handleCollision(), hitClocks, Timers::isClocked(), Timer::isSet(), CollisionSides::left, Character::left(), mAbleToMove, mDamage, mIsMovingRight, EntityBase::removeNonSolid(), CollisionSides::right, Character::right(), Timer::set(), unableToMoveTime, and unableToMoveTimer.
handleNoCollision()
void NPC::handleNoCollision () override virtual
This method handles a no collision.
When this method is called it means there was no collision with anything. This method is called by the Collision class.
Reimplemented from Character.
Definition at line 116 of file NPC.cpp.
References Character::handleNoCollision(), Timer::isSet(), Timer::set(), unableToMoveTime, and unableToMoveTimer.
hurt()
void NPC::hurt (uint_least8_t damage) override virtual
This is a virtual method should be overridden if you want to hurt a EntityBase on damage.
Reimplemented from EntityBase.
Definition at line 123 of file NPC.cpp.
References EntityBase::destroy(), mHealth, and Character::startHurtAnimation().
update()
void NPC::update (const sf::Time & deltaTime) override virtual
This method updates all the values in the Character.
A few values are updated when this function is called.
For example:
Direction/movement is updated
mState is updated
Unperformed actions will be performed
Player animation is called
Reimplemented from Character.
Definition at line 133 of file NPC.cpp.
References Timers::deleteExpired(), hitClocks, Timer::isExpired(), mAbleToMove, mDeltaXMovement, mIsMovingRight, EntityBase::mPosition, mStartPoint, unableToMoveTimer, and Character::update().
Member Data Documentation
hitClocks
Timers NPC::hitClocks private
These are all the clocked objects which are hurt by the NPC.
When something collided with the NPC there will be a Timer added to this object. Only when there is not a timer the NPC is able to hurt him again.
Definition at line 75 of file NPC.hpp.
lastTimeSinceJumpClock
sf::Clock NPC::lastTimeSinceJumpClock private
This clock is used to check how long it has been the NPC jumped for the last time.
The clock will be set when the NPC has jumped. If the value of the clock is greater than mJumpDeltaTime the NPC is able to jump again.
Definition at line 54 of file NPC.hpp.
mAbleToMove
bool NPC::mAbleToMove private
The NPC is able to move if this is true.
The NPC is NOT able to move if this is false.
Definition at line 60 of file NPC.hpp.
mDamage
uint_least8_t NPC::mDamage private
This is the amount of damage the NPC will deal when something hit him.
Definition at line 68 of file NPC.hpp.
mDeltaXMovement
float NPC::mDeltaXMovement private
This is the amount of difference in the X axis the NPC will walk from mStartPoint.
Definition at line 23 of file NPC.hpp.
mHealth
uint_least8_t NPC::mHealth private
This is the amount of health the player got at the moment.
Definition at line 64 of file NPC.hpp.
mIsMovingRight
bool NPC::mIsMovingRight private
The NPC is moving to the right if this is true.
The NPC is moving to the left if this is false.
Definition at line 28 of file NPC.hpp.
mJumpDeltaTime
sf::Time NPC::mJumpDeltaTime private
This is the time there should be between jumps.
Definition at line 45 of file NPC.hpp.
mJumpingEnabled
bool NPC::mJumpingEnabled private
The NPC is able to jump if this is true.
The NPC is NOT able to jump if this is false.
Definition at line 41 of file NPC.hpp.
mStartPoint
sf::Vector2f NPC::mStartPoint private
This is the position where the NPC will spawn at.
Definition at line 19 of file NPC.hpp.
unableToMoveTime
sf::Time NPC::unableToMoveTime = sf::seconds(2) private
The amount of time the NPC is unable to move after a collision.
Definition at line 32 of file NPC.hpp.
unableToMoveTimer
Timer NPC::unableToMoveTimer private
This is a timer used to make the player unable to move for a given time.
Definition at line 36 of file NPC.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Entity/NPC.hpp
C:/test/V2C_V2THGA_2018/src/Entity/NPC.cpp