V2THGA group 1 (MiNd_F*cK): Factory Class Reference
Factory Class Reference
Class used to create objects etc. from a file.
#include <Factory.hpp>
Public Member Functions
Factory ()
Constructor for Factory class.
SettingsData readLevelFile (std::string fileName, std::vector< std::unique_ptr< EntityBase >> &staticObjects, std::vector< std::unique_ptr< EntityBase >> &movableObjects)
Method for the user to interact with the factory.
Private Member Functions
void readCharacters (std::ifstream &text, int amountOfScreens, std::vector< std::unique_ptr< EntityBase >> &movableObjects)
Method to read the characters from the input file.
void createFinishes (std::vector< std::unique_ptr< EntityBase >> &staticObjects)
Method to create finish point.
void readObjects (std::ifstream &text, int amountOfScreens, std::vector< std::unique_ptr< EntityBase >> &staticObjects, std::vector< std::unique_ptr< EntityBase >> &movableObjects)
Method used for reading all the game objects from a level file.
SettingsData readSettings (std::ifstream &text)
A method that reads the settings for the level.
int getNoLines (std::string fileName)
Method used to get the number of lines from a text file;.
std::function< void()> checkDrugName (const std::string &eventName)
Method to check the given name and return the function coresponding to that name.
Private Attributes
std::array< sf::Vector2f, 4 > mFinishPoints
This array holds the finish points for all screens of every level.
std::string mPathPlatform = "../res/Textures/Platform/"
This string holds the path to the Platform textures.
std::string mPathSpike = "../res/Textures/Spike/"
This string holds the path to the Spike textures.
std::string mPathFinish = "../res/Textures/Finish/"
This string holds the path to the Finish textures.
std::string mPathDrugs = "../res/Textures/Drugs/"
This string holds the path to the Drugs textures.
std::string mPathTutorial = "../res/Textures/Tutorial/"
This string holds the path to the Tutorial textures.
int mAmountOfScreens = 0
An int used to store the amount of screens from a level file.
int mNoOfLines = 0
An int used to store the number of lines of a text file.
Detailed Description
Class used to create objects etc. from a file.
Definition at line 45 of file Factory.hpp.
Constructor & Destructor Documentation
Factory()
Factory::Factory () inline
Constructor for Factory class.
Definition at line 138 of file Factory.hpp.
Member Function Documentation
checkDrugName()
std::function< void()> Factory::checkDrugName (const std::string & eventName) private
Method to check the given name and return the function coresponding to that name.
Parameters
eventName The name of the event you want to give to a drug.
Returns
returns the corresponding function to the name.
Definition at line 269 of file Factory.cpp.
References Drugs::both, Drugs::energy, Drugs::energyAdd1, Drugs::energySub2, and Drugs::health.
createFinishes()
void Factory::createFinishes (std::vector< std::unique_ptr< EntityBase >> & staticObjects) private
Method to create finish point.
Uses the contents of mFinishPoints to create finishPoint objects and puts them in the given vector.
Parameters
staticObjects A vector used to hold the static objects for the level.
Definition at line 236 of file Factory.cpp.
References mAmountOfScreens, mFinishPoints, and mPathFinish.
getNoLines()
int Factory::getNoLines (std::string fileName) private
Method used to get the number of lines from a text file;.
Parameters
fileName A string that contains the name of the file or the path to the file.
Returns
Returns the number of lines.
Definition at line 258 of file Factory.cpp.
readCharacters()
void Factory::readCharacters (std::ifstream & text, int amountOfScreens, std::vector< std::unique_ptr< EntityBase >> & movableObjects) private
Method to read the characters from the input file.
This method is used in the readObjects method. It is called when "CHARACTERS" is found in the input file;
Parameters
text This is a opened text file.
amountOfScreens This is the amount of screens that have been specified in the level file.
movableObjects This vector holds all the movable objects of the level.
Definition at line 222 of file Factory.cpp.
readLevelFile()
SettingsData Factory::readLevelFile (std::string fileName, std::vector< std::unique_ptr< EntityBase >> & staticObjects, std::vector< std::unique_ptr< EntityBase >> & movableObjects)
Method for the user to interact with the factory.
This method uses all the other reading methods to give all the data from a level file in one go. It also handles the opening and closing of the file.
Parameters
fileName A string that contains the name of the file or the path to the file.
staticObjects A vector that gets filled with the static game objects from the levvel file.
movableObjects A vector that gets filled with the movable game objects from the levvel file.
Returns
This method returns a SettingData struct and also filles both of the given vectors.
Definition at line 247 of file Factory.cpp.
References getNoLines(), mNoOfLines, SettingsData::noOfScreens, readObjects(), and readSettings().
readObjects()
void Factory::readObjects (std::ifstream & text, int amountOfScreens, std::vector< std::unique_ptr< EntityBase >> & staticObjects, std::vector< std::unique_ptr< EntityBase >> & movableObjects) private
Method used for reading all the game objects from a level file.
This function goes through a text file line by line, and constructs game objects from it.
Parameters
text An opened text file, it contains all the game objects.
amountOfScreens This is the amount of screens that have been specified in the level file.
staticObjects A vector that gets filled with the static game objects from the levvel file.
movableObjects A vector that gets filled with the movable game objects from the levvel file.
Definition at line 84 of file Factory.cpp.
References checkDrugName(), createFinishes(), Drugs::health, mNoOfLines, mPathDrugs, mPathPlatform, mPathSpike, mPathTutorial, and readCharacters().
readSettings()
SettingsData Factory::readSettings (std::ifstream & text) private
A method that reads the settings for the level.
Parameters
text An opened text file, it contains all the game objects.
Definition at line 20 of file Factory.cpp.
References SettingsData::backgroundImages, SettingsData::energy, SettingsData::finishPoints, SettingsData::gameDuration, mAmountOfScreens, mFinishPoints, SettingsData::noOfScreens, SettingsData::songName, and SettingsData::totalLevelSize.
Member Data Documentation
mAmountOfScreens
int Factory::mAmountOfScreens = 0 private
An int used to store the amount of screens from a level file.
Definition at line 120 of file Factory.hpp.
mFinishPoints
std::array<sf::Vector2f, 4> Factory::mFinishPoints private
This array holds the finish points for all screens of every level.
Definition at line 49 of file Factory.hpp.
mNoOfLines
int Factory::mNoOfLines = 0 private
An int used to store the number of lines of a text file.
Definition at line 124 of file Factory.hpp.
mPathDrugs
std::string Factory::mPathDrugs = "../res/Textures/Drugs/" private
This string holds the path to the Drugs textures.
Definition at line 65 of file Factory.hpp.
mPathFinish
std::string Factory::mPathFinish = "../res/Textures/Finish/" private
This string holds the path to the Finish textures.
Definition at line 61 of file Factory.hpp.
mPathPlatform
std::string Factory::mPathPlatform = "../res/Textures/Platform/" private
This string holds the path to the Platform textures.
Definition at line 53 of file Factory.hpp.
mPathSpike
std::string Factory::mPathSpike = "../res/Textures/Spike/" private
This string holds the path to the Spike textures.
Definition at line 57 of file Factory.hpp.
mPathTutorial
std::string Factory::mPathTutorial = "../res/Textures/Tutorial/" private
This string holds the path to the Tutorial textures.
Definition at line 69 of file Factory.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Factory.hpp
C:/test/V2C_V2THGA_2018/src/Factory.cpp