V2THGA group 1 (MiNd_F*cK): ViewManager Class Reference
ViewManager Class Reference
Class to manage the screens/views on 1 renderwindow.
#include <ViewManager.hpp>
Public Member Functions
ViewManager (sf::RenderWindow &mainWindow, const int &noOfScreens)
Constructor for the ViewManager.
void selectMoveScreen (const int &screenNumber)
Function to select a certain screen for moving.
void selectDrawingScreen (const int &screenNumber)
Function to select a certain screen for drawing.
void resetDrawingScreen ()
Function to reset the view to the default view.
void draw (const sf::Drawable &drawable)
Function to draw an sf::Drawable.
void draw (const sf::Vertex *vertices, std::size_t vertexCount, sf::PrimitiveType type)
Function to draw vertices.
void draw (const sf::VertexBuffer &vertexBuffer)
Function to draw an sf::VertexBuffer.
void draw (const sf::VertexBuffer &vertexBuffer, std::size_t firstVertex, std::size_t vertexCount)
Function to draw a part of an sf::VertexBuffer.
void move (const sf::Vector2f &offset)
Function to move view(s).
void display ()
Adaptor function to display the window.
void clear ()
Adaptor function to clear the window.
void close ()
Adaptor function to close the window.
bool isOpen ()
Adaptor function to check if the window is open.
bool pollEvent (sf::Event &e)
Adaptor function to poll events in the window.
sf::Vector2f getViewPosition (const int &screenNumber) const
Function to get the current position of the given view.
sf::Vector2f getViewSize (const int &screenNumber) const
Function to get the current size of the given view.
int getAmountOfScreens ()
Function to get the current amount of screens present in ViewManager.
void changeAmountOfScreens (int newAmount)
Function to change the amount of screens.
void createScreenBorders ()
Function to create the borders around the screens.
void setBordorColor (int screenNumber)
Function to set the bordercolor when selected.
void resetBordorColor (int screenNumber)
Function to set the bordercolor when selected.
virtual ~ViewManager ()
Private Member Functions
sf::Vector2f convertVector2u (const sf::Vector2u &input)
Function that converts a given sf::Vector2u to a sf::Vector2f.
Private Attributes
sf::RenderWindow & mMainWindow
A reference to the main window.
int mAmountOfScreens
The current amount of screen.
sf::Vector2f mOffset = sf::Vector2f(20.f, 20.f)
std::vector< Screen > mScreens
A vector that contains all the separate screens.
std::array< sf::RectangleShape, 4 > mBorders
Detailed Description
Class to manage the screens/views on 1 renderwindow.
Definition at line 27 of file ViewManager.hpp.
Constructor & Destructor Documentation
ViewManager()
ViewManager::ViewManager (sf::RenderWindow & mainWindow, const int & noOfScreens)
Constructor for the ViewManager.
Contructs the ViewManager on basis of the parameters.
Parameters
mainWindow The window on which de ViewManager is based.
noOfScreens The number of screens that need to be made. Choices: 1,2,4.
Definition at line 10 of file ViewManager.cpp.
References changeAmountOfScreens(), mAmountOfScreens, mMainWindow, and mScreens.
~ViewManager()
ViewManager::~ViewManager () virtual
Definition at line 20 of file ViewManager.cpp.
Member Function Documentation
changeAmountOfScreens()
void ViewManager::changeAmountOfScreens (int newAmount)
Function to change the amount of screens.
This function changes the amount of screens dynamically.
Parameters
newAmount The new amount of screens that need to be created.
Definition at line 168 of file ViewManager.cpp.
References convertVector2u(), createScreenBorders(), mAmountOfScreens, mMainWindow, mScreens, resetDrawingScreen(), and Screen::view.
clear()
void ViewManager::clear ()
Adaptor function to clear the window.
Definition at line 130 of file ViewManager.cpp.
References mMainWindow.
close()
void ViewManager::close ()
Adaptor function to close the window.
Definition at line 134 of file ViewManager.cpp.
References mMainWindow.
convertVector2u()
sf::Vector2f ViewManager::convertVector2u (const sf::Vector2u & input) private
Function that converts a given sf::Vector2u to a sf::Vector2f.
Definition at line 5 of file ViewManager.cpp.
createScreenBorders()
void ViewManager::createScreenBorders ()
Function to create the borders around the screens.
Definition at line 24 of file ViewManager.cpp.
References mAmountOfScreens, mBorders, mMainWindow, and mScreens.
display()
void ViewManager::display ()
Adaptor function to display the window.
Definition at line 122 of file ViewManager.cpp.
References mAmountOfScreens, mBorders, mMainWindow, and resetDrawingScreen().
draw() [1/4]
void ViewManager::draw (const sf::Drawable & drawable)
Function to draw an sf::Drawable.
Parameters
drawable The object that needs to de drawn.
Definition at line 98 of file ViewManager.cpp.
References mMainWindow.
draw() [2/4]
void ViewManager::draw (const sf::Vertex * vertices, std::size_t vertexCount, sf::PrimitiveType type)
Function to draw vertices.
Parameters
vertices The vertices that need to be draw.
vertexCount The amount of vertices.
type The type of vertices for example sf::Lines.
Definition at line 102 of file ViewManager.cpp.
References mMainWindow.
draw() [3/4]
void ViewManager::draw (const sf::VertexBuffer & vertexBuffer)
Function to draw an sf::VertexBuffer.
Parameters
vertexBuffer The sf::VertexBuffer that needs to be drawn.
Definition at line 106 of file ViewManager.cpp.
References mMainWindow.
draw() [4/4]
void ViewManager::draw (const sf::VertexBuffer & vertexBuffer, std::size_t firstVertex, std::size_t vertexCount)
Function to draw a part of an sf::VertexBuffer.
Parameters
vertexBuffer The sf::VertexBuffer that needs to be drawn.
firstVertex The vertex on which the drawing should start.
vertexCount The amount of vertices.
Definition at line 110 of file ViewManager.cpp.
References mMainWindow.
getAmountOfScreens()
int ViewManager::getAmountOfScreens ()
Function to get the current amount of screens present in ViewManager.
Returns
Returns the current amount of screens.
Definition at line 164 of file ViewManager.cpp.
References mAmountOfScreens.
getViewPosition()
sf::Vector2f ViewManager::getViewPosition (const int & screenNumber) const
Function to get the current position of the given view.
Parameters
screenNumber The number of the screen you want to get the position from.
Returns
Return the position of the view.
Definition at line 146 of file ViewManager.cpp.
References mScreens.
getViewSize()
sf::Vector2f ViewManager::getViewSize (const int & screenNumber) const
Function to get the current size of the given view.
Parameters
screenNumber The number of the screen you want to get the size from.
Returns
Return the size of the view.
Definition at line 155 of file ViewManager.cpp.
References mScreens.
isOpen()
bool ViewManager::isOpen ()
Adaptor function to check if the window is open.
Returns
bool Returns true if window is open.
Definition at line 138 of file ViewManager.cpp.
References mMainWindow.
move()
void ViewManager::move (const sf::Vector2f & offset)
Function to move view(s).
This function moves all the selected views.
Parameters
offset The offset on basis of which the views need to be moved.
Definition at line 114 of file ViewManager.cpp.
References mScreens.
pollEvent()
bool ViewManager::pollEvent (sf::Event & e)
Adaptor function to poll events in the window.
Definition at line 142 of file ViewManager.cpp.
References mMainWindow.
resetBordorColor()
void ViewManager::resetBordorColor (int screenNumber)
Function to set the bordercolor when selected.
Bordor color is White when deselected.
Parameters
screenNumber The screen number of the screen the color needs to be set.
Definition at line 69 of file ViewManager.cpp.
References mBorders.
resetDrawingScreen()
void ViewManager::resetDrawingScreen ()
Function to reset the view to the default view.
Definition at line 94 of file ViewManager.cpp.
References mMainWindow.
selectDrawingScreen()
void ViewManager::selectDrawingScreen (const int & screenNumber)
Function to select a certain screen for drawing.
Use this function before you draw to select where you want the object to be drawn.
Giving 0 as a screen number selects the default view.
Parameters
screenNumber The number of the screen you want to select.
Definition at line 83 of file ViewManager.cpp.
References mMainWindow, mScreens, and resetDrawingScreen().
selectMoveScreen()
void ViewManager::selectMoveScreen (const int & screenNumber)
Function to select a certain screen for moving.
This function selects a screen note: multiple screens can be selected at once.
Parameters
screenNumber The number of the screen you want to select.
Definition at line 75 of file ViewManager.cpp.
References mScreens.
setBordorColor()
void ViewManager::setBordorColor (int screenNumber)
Function to set the bordercolor when selected.
Bordor color is Red when selected.
Parameters
screenNumber The screen number of the screen the color needs to be set.
Definition at line 63 of file ViewManager.cpp.
References mBorders.
Member Data Documentation
mAmountOfScreens
int ViewManager::mAmountOfScreens private
The current amount of screen.
Definition at line 35 of file ViewManager.hpp.
mBorders
std::array<sf::RectangleShape, 4> ViewManager::mBorders private
Definition at line 46 of file ViewManager.hpp.
mMainWindow
sf::RenderWindow& ViewManager::mMainWindow private
A reference to the main window.
Definition at line 31 of file ViewManager.hpp.
mOffset
sf::Vector2f ViewManager::mOffset = sf::Vector2f(20.f, 20.f) private
Definition at line 37 of file ViewManager.hpp.
mScreens
std::vector<Screen> ViewManager::mScreens private
A vector that contains all the separate screens.
This vector contains screens on the basis of the screen struct. The most screens at this point in time is 4.
Definition at line 44 of file ViewManager.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/ViewManager.hpp
C:/test/V2C_V2THGA_2018/src/ViewManager.cpp