V2THGA group 1 (MiNd_F*cK): Character Class Reference
Character Class Reference
This is the Character class.
#include <Character.hpp>
Public Types
enum State {
State::Idle, State::Moving, State::Running, State::Jumping,
State::Falling, State::Shooting
}
enum Action {
Action::Left, Action::Right, Action::Jump, Action::Run,
Action::Shoot, Action::None
}
The actions which a Character is able to perform.
Public Member Functions
Character (const sf::Vector2f &position, const sf::Vector2f &size, int screenNumber, const sf::Vector2f &maxVelocity, const sf::Vector2f &acceleration, const std::string &characterSheetPath)
This is the constructor of the Character class.
virtual ~Character () override
void addAction (const Action &newAction)
This method adds a new action to mUnperformedActions.
void bindAction (const EventManager &event)
This method binds an event to an action.
virtual void bindActions ()
This method is should be overridden if you want to bind multiple actions at once.
void bindAnimation (const State &state, const AnimationSequence &animationSequence)
This method binds a state to an AnimationSequence.
virtual void bindAnimations ()
This method should be overridden if you want to bind multiple animations at once.
void move (sf::Vector2f &delta)
This method moves the Character.
void applyMovement (const Action &direction)
This method is used to apply the right movement given an action using the velocity.
void updateFacingDirection ()
This method updates the facing direction.
void updateVelocity (const sf::Vector2f &deltaVelocity)
This method adds a given delta velocity to the current mVelocity.
void resetVelocityY ()
This method sets the Y direction of mVelocity to 0.
void resetVelocityX ()
This method sets the X direction of mVelocity to 0.
bool isMovingX () const
This method checks whether the Character is moving in the X direction.
void updateState (const Action &action)
This function updates the current state of the Character.
void startHurtAnimation ()
This method starts the hurting animation.
void animate (const sf::Time &deltaTime)
This method is used to animate the Character his movement.
void left ()
This method moves the Character to the left using applyMovement.
void right ()
This method moves the Character to the right using applyMovement.
void jump ()
This method makes the Character jump into the air.
void run ()
This method makes the Character run using applyMovement.
virtual bool shoot ()
This method is used to shoot a projectile.
virtual bool isShooting () const
This method returns the value of mIsShooting.
std::optional< std::unique_ptr< EntityBase > > getProjectile ()
This method returns a projectile when the Character is shooting.
void performAction (const Action &unperformedAction)
This method performs the given action.
virtual sf::Vector2f getSize () const override
This method returns the size of the Character.
virtual sf::FloatRect getGlobalBounds () const override
This method returns the global bounds of the Character.
void setSpriteScale (float x, float y)
This method sets the scale of mSprite and updates mSize accordingly.
void updateSizeUsingSprite ()
This method updates mSize using the global bounds of mSprite.
virtual bool isFinished () const override
This method returns the value of mIsFinished.
virtual void handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) override
This method handles the collision for a Character.
virtual void handleNoCollision () override
This method handles a no collision.
virtual void update (const sf::Time &deltaTime) override
This method updates all the values in the Character.
virtual void draw (sf::RenderWindow &window) override
This method draws the Character to a sf::RenderWindow.
virtual void draw (ViewManager &window) override
This method draws the Character to a ViewManager.
Public Member Functions inherited from EntityBase
EntityBase (const sf::Vector2f &position, const sf::Vector2f size, int screenNumber, bool isSolid=true, bool isVisible=true)
This is the constructor for the EntityBase class.
virtual ~EntityBase ()
uint_least64_t getId () const
A method to get the id.
void move (float deltaX, float deltaY)
This method moves the EntityBase by adding the delta to mPosition.
void move (const sf::Vector2f &deltaPosition)
This method moves the EntityBase by adding the delta to mPosition.
void setScreenNumber (int newScreenNumber)
This method sets the screenNumber.
int getScreenNumber () const
This method returns the value of mScreenNumber.
void setIsVisible (bool isVisible)
This method sets mIsVisible.
bool isVisible () const
This method returns mScreenNumber.
void setIsSolid (bool isSolid)
This method sets mIsSolid.
bool isSolid () const
This method returns the value of mIsSolid.
void destroy ()
This method sets mShouldDestroy to true.
bool shouldDestroy () const
This method returns mIsSolid.
virtual void hurt (uint_least8_t damage)
This is a virtual method should be overridden if you want to hurt a EntityBase on damage.
void setPosition (float x, float y)
This method sets mPosition.
virtual void setPosition (const sf::Vector2f &newPosition)
This method sets mPosition.
void setSize (const sf::Vector2f &newSize)
This method sets mSize.
virtual sf::Vector2f getPosition () const
This method returns the value of mPosition.
virtual sf::Vector2f getNextPosition () const
This method returns the next position the EntityBase will be.
void removeNonSolid (std::vector< std::unique_ptr< EntityBase > *> &top, std::vector< std::unique_ptr< EntityBase > *> &bottom, std::vector< std::unique_ptr< EntityBase > *> &left, std::vector< std::unique_ptr< EntityBase > *> &right, CollisionSides &hitSides) const
This method removes the non solid objects from the vector.
virtual void setColor (const sf::Color &newColor)
This method handles changing color if overridden.
void drawIfVisible (sf::RenderWindow &window)
This method draws to the sf::RenderWindow if mIsVisible is true.
void drawIfVisible (ViewManager &window)
This method draws to the ViewManager if mIsVisible is true.
Protected Attributes
uint_least64_t id
The id of a Character used to identify which Character it is.
sf::Vector2f mVelocity
The current velocity of the Character used to move the Character.
sf::Vector2f mMaxVelocity
The mamixum velocity of the Character. The Character is not able to exceed this velocity.
sf::Vector2f mAcceleration
The amount of acceleration of the Character.
bool mIsFacingRight
The Character is facing right if this is true.
The Character is facing left if this is false.
bool mIsInAir
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mIsJumping
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mCanDoubleJump
The Character is in the air if this is true.
The Character is not on the ground if this is false.
bool mIsRunning
The Character is running if this is true.
The Character is not running if this is false.
bool mIsShooting
The Character is shooting if this is true.
The Character is not shooting if this is false.
bool mIsFinished
The Character is finished if this is true.
The Character is not finished if this is false.
State mPreviousState
The previous state the Character was in.
State mState
The current state the character is in.
sf::Texture mTexture
The texture of the Character.
sf::Sprite mSprite
The sprite of the Character.
bool mIsHurting = false
The Character is hurting if this is true.
The Character is not hurting if this is false.
CollisionSides mRestrictedSides
The direction in which the character can not walk.
float mGravity = 0.0f
The amount of pixels the character moves down each update.
This only occurs if the character is in air.
float mStartingJumpForce = -7.0f
The amount of pixels the character moves up when the jump starts.
float mJumpForce = mStartingJumpForce
The amount of pixels the character moves up each update.
This only occurs if the character is jumping.
float mMaxGravity = 7.0f
The maximum amount of pixels the character moves down each update.
float mJumpAcceleration = 0.3f
The amount of pixels the mJumpForce is decreased by each update.
float mGravityAcceleration = 0.3f
The amount of pixels the mGravity is increased by each update.
Timer mShootTimer
The timer to stop the Character from shooting continuously.
sf::Time mTimeBetweenShots = sf::seconds(1)
The time there is between shots.
sf::Time mTimeSinceLastAnimation
The last time a new picture has been set during a AnimationSequence.
Timer mHurtTimer
The timer used to check if the hurt animation should stop.
sf::Time mTotalHurtTime = sf::seconds(1)
The time the hurt animation is shown.
std::queue< Action > mUnperformedActions = {}
All the unperformed actions. These will be performed in the update method.
sf::Vector2i currentSprite = sf::Vector2i(0,0)
The current location in the spritesheet.
std::vector< std::pair< Action, std::function< void()> > > mActions
These are all the possible actions which can be performed.
std::vector< std::pair< State, AnimationSequence > > mAnimations = {}
These are all the states which should be filled in any derived class.
std::vector< EventManager > actions = {}
These are all the events/actions the Character has.
Protected Attributes inherited from EntityBase
uint_least64_t id
The id of the EntityBase.
sf::Vector2f mPosition
The position of the EntityBase in the world.
sf::Vector2f mSize
The size of the EntityBase.
int mScreenNumber
The screen the EntityBase should be drawn to.
bool mIsVisible
The EntityBase is visible on the screen if this is true.
The EntityBase is NOT visible on the screen if this is false.
.
bool mIsSolid
The EntityBase is solid on the screen if this is true.
The EntityBase is NOT solid on the screen if this is false.
.
bool mShouldDestroyed
The EntityBase should be destroyed if this is true.
The EntityBase should NOT be destroyed if this is false.
.
Additional Inherited Members
Static Public Member Functions inherited from EntityBase
static void backToStartId ()
Set the nextId to zero. (Reset)
Static Protected Attributes inherited from EntityBase
static uint_least64_t nextId = 0
The first id which is free to use for a new EntityBase object.
Detailed Description
This is the Character class.
This class is used to make non playable characters and players for the game. The methods shared among all the characters in the game are in this class.
Definition at line 68 of file Character.hpp.
Member Enumeration Documentation
Action
enum Character::Action strong
The actions which a Character is able to perform.
These actions are given to the performAction method to perform a given action. After calling the perform method the state is automatically updated if the state of the Character changed.
Enumerator
Left
Right
< The Character is going to the left side.
Jump
< The Character is going to the right side.
Run
< The Character is going to jump in the air.
Shoot
< The Character is going to run.
None
< The Character is going to shoot a energy bolt.
< The Character is going to do nothing. Also known as Idle.
Definition at line 89 of file Character.hpp.
State
enum Character::State strong
/brief This are all the states a Character could be in.
These states are mostly used to choose the right animation of the Character. mState will be updated using the updateState method.
Enumerator
Idle
Moving
< The Character is doing nothing.
Running
< The Character is walking.
Jumping
< The Character is running.
Falling
< The Character is jumping.
Shooting
< The Character is falling.
Definition at line 75 of file Character.hpp.
Constructor & Destructor Documentation
Character()
Character::Character (const sf::Vector2f & position, const sf::Vector2f & size, int screenNumber, const sf::Vector2f & maxVelocity, const sf::Vector2f & acceleration, const std::string & characterSheetPath)
This is the constructor of the Character class.
Parameters
position The position the Character should spawn.
size The size of the Character. Most of the time the same size as one single picture in the sprite
screenNumber The screen number on which the player needs to be drawn.
maxVelocity The maximum velocity the Character is able to move at.
acceleration The amount of speed the Character gains per update if moving in a direction.
characterSheetPath The path to the spritesheet of the Character.
Definition at line 15 of file Character.cpp.
References bindActions(), bindAnimations(), EntityBase::mPosition, EntityBase::mSize, mSprite, and mTexture.
~Character()
Character::~Character () override virtual
Definition at line 51 of file Character.cpp.
Member Function Documentation
addAction()
void Character::addAction (const Action & newAction)
This method adds a new action to mUnperformedActions.
The action will be performed the next time the all the unperformed actions will be called.
Parameters
newAction The action you want to add to the unperformed actions.
Definition at line 53 of file Character.cpp.
References mUnperformedActions.
animate()
void Character::animate (const sf::Time & deltaTime)
This method is used to animate the Character his movement.
This method is used to show the Character's animation on the screen. This is done using a vector containing std::pairs, this vector is called mAnimations. The vector is filled using bindAnimation and bindAnimations. In this vector the first item of the pair is the state and the second the AnimationSequence that should be displayed in that state.
Parameters
deltaTime The amount of time between the past update and this update. This is used to check whether a new picture should be selected.
Definition at line 389 of file Character.cpp.
References currentSprite, Timer::isExpired(), EntityBase::isVisible(), mAnimations, mHurtTimer, mIsFacingRight, mIsHurting, mPreviousState, EntityBase::mSize, mSprite, mState, mTimeSinceLastAnimation, EntityBase::setIsVisible(), and updateFacingDirection().
applyMovement()
void Character::applyMovement (const Action & direction)
This method is used to apply the right movement given an action using the velocity.
If the direction is left the Character will move left and vise versa. The method updates mVelocity.
Parameters
direction The direction you want to move in.
Definition at line 86 of file Character.cpp.
References Jump, Left, mAcceleration, mStartingJumpForce, mVelocity, Right, and updateVelocity().
bindAction()
void Character::bindAction (const EventManager & event)
This method binds an event to an action.
This is used to bind keybindings or other conditions to perform an action.
Parameters
event The event you want to bind the a given action.
Definition at line 57 of file Character.cpp.
References actions.
bindActions()
virtual void Character::bindActions () inline virtual
This method is should be overridden if you want to bind multiple actions at once.
This method is called on construction.
Reimplemented in Player, and NPC.
Definition at line 143 of file Character.hpp.
bindAnimation()
void Character::bindAnimation (const State & state, const AnimationSequence & animationSequence)
This method binds a state to an AnimationSequence.
The animation of the AnimationSequence will be performed when the Character is in the given state.
Parameters
state The state you want to bind to an animation.
animationSequence The animation you want to bind to a given state.
Definition at line 61 of file Character.cpp.
References mAnimations.
bindAnimations()
virtual void Character::bindAnimations () inline virtual
This method should be overridden if you want to bind multiple animations at once.
This method is called on construction.
Reimplemented in Player, and NPC.
Definition at line 163 of file Character.hpp.
draw() [1/2]
void Character::draw (sf::RenderWindow & window) override virtual
This method draws the Character to a sf::RenderWindow.
Implements EntityBase.
Definition at line 451 of file Character.cpp.
References mSprite.
draw() [2/2]
void Character::draw (ViewManager & window) override virtual
This method draws the Character to a ViewManager.
Warning
A screen inside the ViewManager must be selected before drawing.
Implements EntityBase.
Definition at line 455 of file Character.cpp.
References ViewManager::draw(), EntityBase::mScreenNumber, mSprite, and ViewManager::selectDrawingScreen().
getGlobalBounds()
sf::FloatRect Character::getGlobalBounds () const override virtual
This method returns the global bounds of the Character.
Returns
a Sf::FloatRect containing the global bounds of the Character.
Reimplemented from EntityBase.
Definition at line 282 of file Character.cpp.
References mSprite.
getProjectile()
std::optional< std::unique_ptr< EntityBase > > Character::getProjectile ()
This method returns a projectile when the Character is shooting.
Using this method a new projectile is made. This projectile exists until a collision is detected.
Returns
An std::optional containing a projectile when mIsShooting is true. if mIsShooting is false the std::optional is empty.
Definition at line 247 of file Character.cpp.
References EntityBase::getPosition(), EntityBase::getScreenNumber(), getSize(), mIsFacingRight, and mIsShooting.
getSize()
sf::Vector2f Character::getSize () const override virtual
This method returns the size of the Character.
Returns
A sf::Vector2f containing the size of the Character.
Reimplemented from EntityBase.
Definition at line 275 of file Character.cpp.
References mSprite.
handleCollision()
void Character::handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) override virtual
This method handles the collision for a Character.
This method is called by the Collision class. In this method the restrictedSides is updated, mIsInAir is set to false when the Character hits the ground, the position is set correctly when standing on a moving object, etc. If you want a more in depth view of what's happening in this method. You should check the defintion.
Reimplemented from EntityBase.
Reimplemented in Player, and NPC.
Definition at line 302 of file Character.cpp.
References CollisionSides::bottom, CollisionSides::left, left(), mCanDoubleJump, mIsInAir, mIsJumping, mRestrictedSides, mVelocity, EntityBase::removeNonSolid(), CollisionSides::right, right(), and CollisionSides::top.
handleNoCollision()
void Character::handleNoCollision () override virtual
This method handles a no collision.
When this method is called it means there was no collision with anything. This method is called by the Collision class.
Reimplemented from EntityBase.
Reimplemented in NPC.
Definition at line 338 of file Character.cpp.
References mIsInAir, and mRestrictedSides.
isFinished()
bool Character::isFinished () const override virtual
This method returns the value of mIsFinished.
Returns
A bool containing the value of mIsFinished.
Reimplemented from EntityBase.
Definition at line 298 of file Character.cpp.
References mIsFinished.
isMovingX()
bool Character::isMovingX () const
This method checks whether the Character is moving in the X direction.
If mVelocity.x is 0 this method will return false otherwise it will return true.
Definition at line 136 of file Character.cpp.
References mVelocity.
isShooting()
bool Character::isShooting () const virtual
This method returns the value of mIsShooting.
Returns
A bool containing the value of mIsShooting.
Definition at line 243 of file Character.cpp.
References mIsShooting.
jump()
void Character::jump ()
This method makes the Character jump into the air.
A Character is able to single jump and double jump. Double jump can only be triggered when you are falling down after jumping.
Definition at line 212 of file Character.cpp.
References applyMovement(), Jump, mCanDoubleJump, mIsInAir, mIsJumping, mJumpForce, and mStartingJumpForce.
left()
void Character::left ()
This method moves the Character to the left using applyMovement.
Definition at line 204 of file Character.cpp.
References applyMovement(), and Left.
move()
void Character::move (sf::Vector2f & delta)
This method moves the Character.
Parameters
delta The delta position you want to move the player.
This method moves the Character using the delta. The Character will only move to the side is not restricted.
Definition at line 68 of file Character.cpp.
References CollisionSides::bottom, CollisionSides::left, EntityBase::move(), EntityBase::mPosition, mRestrictedSides, mSprite, CollisionSides::right, and CollisionSides::top.
performAction()
void Character::performAction (const Action & unperformedAction)
This method performs the given action.
Parameters
unperformedAction This is the action you want to perform.
Definition at line 265 of file Character.cpp.
References mActions, and updateState().
resetVelocityX()
void Character::resetVelocityX ()
This method sets the X direction of mVelocity to 0.
Definition at line 132 of file Character.cpp.
References mVelocity.
resetVelocityY()
void Character::resetVelocityY ()
This method sets the Y direction of mVelocity to 0.
Definition at line 128 of file Character.cpp.
References mVelocity.
right()
void Character::right ()
This method moves the Character to the right using applyMovement.
Definition at line 208 of file Character.cpp.
References applyMovement(), and Right.
run()
void Character::run ()
This method makes the Character run using applyMovement.
Definition at line 227 of file Character.cpp.
References applyMovement(), mIsInAir, mIsJumping, mIsRunning, and Run.
setSpriteScale()
void Character::setSpriteScale (float x, float y)
This method sets the scale of mSprite and updates mSize accordingly.
Definition at line 286 of file Character.cpp.
References mSprite, and updateSizeUsingSprite().
shoot()
bool Character::shoot () virtual
This method is used to shoot a projectile.
When mShootTimer is expired the Character is able to shoot. mShootTimer is restarted and mIsShooting is set to true.
Returns
A bool containing whether the player was able to shoot or not.
Reimplemented in Player.
Definition at line 234 of file Character.cpp.
References Timer::isExpired(), mIsShooting, mShootTimer, mTimeBetweenShots, and Timer::set().
startHurtAnimation()
void Character::startHurtAnimation ()
This method starts the hurting animation.
The hurtClock is restarted and mIsHurting is set to true. The player starts now starts flickering. This flickering animation is handled by the animate method. Everytime a new picture is being set in the animate method setIsVisible is toggled.
Definition at line 199 of file Character.cpp.
References mHurtTimer, mIsHurting, mTotalHurtTime, and Timer::set().
update()
void Character::update (const sf::Time & deltaTime) override virtual
This method updates all the values in the Character.
A few values are updated when this function is called.
For example:
Direction/movement is updated
mState is updated
Unperformed actions will be performed
Player animation is called
Implements EntityBase.
Reimplemented in NPC.
Definition at line 343 of file Character.cpp.
References actions, animate(), CollisionSides::bottom, mGravity, mGravityAcceleration, mIsInAir, mIsJumping, mIsRunning, mJumpAcceleration, mJumpForce, mMaxGravity, move(), mRestrictedSides, mStartingJumpForce, mUnperformedActions, mVelocity, None, performAction(), Run, and updateState().
updateFacingDirection()
void Character::updateFacingDirection ()
This method updates the facing direction.
mIsFacingRight will be set to true if the player is moving right. When the player is moving left it will be set to false. When the player is not moving the same direction the player was facing before will be kept.
Definition at line 109 of file Character.cpp.
References mIsFacingRight, and mVelocity.
updateSizeUsingSprite()
void Character::updateSizeUsingSprite ()
This method updates mSize using the global bounds of mSprite.
Definition at line 291 of file Character.cpp.
References EntityBase::mSize, and mSprite.
updateState()
void Character::updateState (const Action & action)
This function updates the current state of the Character.
A parameter action is passed into this method, using that action the new mState is determent.
Parameters
action This is the action the Character is currently performing.
Definition at line 140 of file Character.cpp.
References Falling, Idle, isMovingX(), Jump, Jumping, Left, mIsInAir, Moving, mState, mVelocity, None, Right, Run, Running, Shoot, and updateFacingDirection().
updateVelocity()
void Character::updateVelocity (const sf::Vector2f & deltaVelocity)
This method adds a given delta velocity to the current mVelocity.
mVelocity is updated and kept under the (-)mMaxVelocity. When the Character is running the mMaxVelocity is multiplied by 2.
Parameters
deltaVelocity This is the velocity you want to add to mVelocity.
Definition at line 117 of file Character.cpp.
References mIsRunning, mMaxVelocity, and mVelocity.
Member Data Documentation
actions
std::vector<EventManager> Character::actions = {} protected
These are all the events/actions the Character has.
You should bind these in the derived class.
Definition at line 538 of file Character.hpp.
currentSprite
sf::Vector2i Character::currentSprite = sf::Vector2i(0,0) protected
The current location in the spritesheet.
The pixel location is calculated using the size.
Definition at line 503 of file Character.hpp.
id
uint_least64_t Character::id protected
The id of a Character used to identify which Character it is.
Definition at line 372 of file Character.hpp.
mAcceleration
sf::Vector2f Character::mAcceleration protected
The amount of acceleration of the Character.
Definition at line 386 of file Character.hpp.
mActions
std::vector< std::pair<Action, std::function<void()> > > Character::mActions protected
Initial value:
= {
        std::make_pair(
            Action::Left,   [this](){left();}
        ),
        std::make_pair(
            Action::Right,  [this](){right();}
        ),
        std::make_pair(
            Action::Jump,   [this](){jump();}
        ),
        std::make_pair(
            Action::Run,    [this](){run();}
        ),
        std::make_pair(
            Action::Shoot,  [this](){shoot();}
        ),
    }
These are all the possible actions which can be performed.
When performAction is called the right action is searched in this vector and the std::function is called.
Definition at line 510 of file Character.hpp.
mAnimations
std::vector<std::pair<State, AnimationSequence> > Character::mAnimations = {} protected
These are all the states which should be filled in any derived class.
You should bind these in the derived class.
Definition at line 532 of file Character.hpp.
mCanDoubleJump
bool Character::mCanDoubleJump protected
The Character is in the air if this is true.
The Character is not on the ground if this is false.
Definition at line 406 of file Character.hpp.
mGravity
float Character::mGravity = 0.0f protected
The amount of pixels the character moves down each update.
This only occurs if the character is in air.
Definition at line 451 of file Character.hpp.
mGravityAcceleration
float Character::mGravityAcceleration = 0.3f protected
The amount of pixels the mGravity is increased by each update.
Definition at line 472 of file Character.hpp.
mHurtTimer
Timer Character::mHurtTimer protected
The timer used to check if the hurt animation should stop.
Definition at line 488 of file Character.hpp.
mIsFacingRight
bool Character::mIsFacingRight protected
The Character is facing right if this is true.
The Character is facing left if this is false.
Definition at line 391 of file Character.hpp.
mIsFinished
bool Character::mIsFinished protected
The Character is finished if this is true.
The Character is not finished if this is false.
Definition at line 421 of file Character.hpp.
mIsHurting
bool Character::mIsHurting = false protected
The Character is hurting if this is true.
The Character is not hurting if this is false.
Definition at line 442 of file Character.hpp.
mIsInAir
bool Character::mIsInAir protected
The Character is in the air if this is true.
The Character is on the ground if this is false.
Definition at line 396 of file Character.hpp.
mIsJumping
bool Character::mIsJumping protected
The Character is in the air if this is true.
The Character is on the ground if this is false.
Definition at line 401 of file Character.hpp.
mIsRunning
bool Character::mIsRunning protected
The Character is running if this is true.
The Character is not running if this is false.
Definition at line 411 of file Character.hpp.
mIsShooting
bool Character::mIsShooting protected
The Character is shooting if this is true.
The Character is not shooting if this is false.
Definition at line 416 of file Character.hpp.
mJumpAcceleration
float Character::mJumpAcceleration = 0.3f protected
The amount of pixels the mJumpForce is decreased by each update.
Definition at line 468 of file Character.hpp.
mJumpForce
float Character::mJumpForce = mStartingJumpForce protected
The amount of pixels the character moves up each update.
This only occurs if the character is jumping.
Definition at line 460 of file Character.hpp.
mMaxGravity
float Character::mMaxGravity = 7.0f protected
The maximum amount of pixels the character moves down each update.
Definition at line 464 of file Character.hpp.
mMaxVelocity
sf::Vector2f Character::mMaxVelocity protected
The mamixum velocity of the Character. The Character is not able to exceed this velocity.
Definition at line 382 of file Character.hpp.
mPreviousState
State Character::mPreviousState protected
The previous state the Character was in.
Definition at line 425 of file Character.hpp.
mRestrictedSides
CollisionSides Character::mRestrictedSides protected
The direction in which the character can not walk.
Definition at line 446 of file Character.hpp.
mShootTimer
Timer Character::mShootTimer protected
The timer to stop the Character from shooting continuously.
Definition at line 476 of file Character.hpp.
mSprite
sf::Sprite Character::mSprite protected
The sprite of the Character.
Definition at line 437 of file Character.hpp.
mStartingJumpForce
float Character::mStartingJumpForce = -7.0f protected
The amount of pixels the character moves up when the jump starts.
Definition at line 455 of file Character.hpp.
mState
State Character::mState protected
The current state the character is in.
Definition at line 429 of file Character.hpp.
mTexture
sf::Texture Character::mTexture protected
The texture of the Character.
Definition at line 433 of file Character.hpp.
mTimeBetweenShots
sf::Time Character::mTimeBetweenShots = sf::seconds(1) protected
The time there is between shots.
Definition at line 480 of file Character.hpp.
mTimeSinceLastAnimation
sf::Time Character::mTimeSinceLastAnimation protected
The last time a new picture has been set during a AnimationSequence.
Definition at line 484 of file Character.hpp.
mTotalHurtTime
sf::Time Character::mTotalHurtTime = sf::seconds(1) protected
The time the hurt animation is shown.
Definition at line 492 of file Character.hpp.
mUnperformedActions
std::queue<Action> Character::mUnperformedActions = {} protected
All the unperformed actions. These will be performed in the update method.
Definition at line 497 of file Character.hpp.
mVelocity
sf::Vector2f Character::mVelocity protected
The current velocity of the Character used to move the Character.
Definition at line 377 of file Character.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Entity/Character.hpp
C:/test/V2C_V2THGA_2018/src/Entity/Character.cpp