V2THGA group 1 (MiNd_F*cK): EntityBase Class Reference
EntityBase Class Reference abstract
This is a general class for every entity in the game world.
#include <EntityBase.hpp>
Public Member Functions
EntityBase (const sf::Vector2f &position, const sf::Vector2f size, int screenNumber, bool isSolid=true, bool isVisible=true)
This is the constructor for the EntityBase class.
virtual ~EntityBase ()
uint_least64_t getId () const
A method to get the id.
void move (float deltaX, float deltaY)
This method moves the EntityBase by adding the delta to mPosition.
void move (const sf::Vector2f &deltaPosition)
This method moves the EntityBase by adding the delta to mPosition.
void setScreenNumber (int newScreenNumber)
This method sets the screenNumber.
int getScreenNumber () const
This method returns the value of mScreenNumber.
void setIsVisible (bool isVisible)
This method sets mIsVisible.
bool isVisible () const
This method returns mScreenNumber.
void setIsSolid (bool isSolid)
This method sets mIsSolid.
bool isSolid () const
This method returns the value of mIsSolid.
void destroy ()
This method sets mShouldDestroy to true.
bool shouldDestroy () const
This method returns mIsSolid.
virtual void hurt (uint_least8_t damage)
This is a virtual method should be overridden if you want to hurt a EntityBase on damage.
void setPosition (float x, float y)
This method sets mPosition.
virtual void setPosition (const sf::Vector2f &newPosition)
This method sets mPosition.
void setSize (const sf::Vector2f &newSize)
This method sets mSize.
virtual sf::Vector2f getSize () const
This method returns the value of mSize.
virtual sf::Vector2f getPosition () const
This method returns the value of mPosition.
virtual sf::Vector2f getNextPosition () const
This method returns the next position the EntityBase will be.
virtual sf::FloatRect getGlobalBounds () const
This method returns the global bounds of the EntityBase.
virtual bool isFinished () const
This method is used to check if the EntityBase is finished.
virtual void update (const sf::Time &deltaTime)=0
A pure virtual method used to update the EntityBase.
virtual void handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides)
Function used to handle collisions.
virtual void handleNoCollision ()
This function is called when no collision is detected.
void removeNonSolid (std::vector< std::unique_ptr< EntityBase > *> &top, std::vector< std::unique_ptr< EntityBase > *> &bottom, std::vector< std::unique_ptr< EntityBase > *> &left, std::vector< std::unique_ptr< EntityBase > *> &right, CollisionSides &hitSides) const
This method removes the non solid objects from the vector.
virtual void setColor (const sf::Color &newColor)
This method handles changing color if overridden.
void drawIfVisible (sf::RenderWindow &window)
This method draws to the sf::RenderWindow if mIsVisible is true.
void drawIfVisible (ViewManager &window)
This method draws to the ViewManager if mIsVisible is true.
virtual void draw (sf::RenderWindow &window)=0
This pure virtual method draws the EntityBase to the sf::RenderWindow.
virtual void draw (ViewManager &window)=0
This pure virtual method draws to the sf::RenderWindow.
Static Public Member Functions
static void backToStartId ()
Set the nextId to zero. (Reset)
Protected Attributes
uint_least64_t id
The id of the EntityBase.
sf::Vector2f mPosition
The position of the EntityBase in the world.
sf::Vector2f mSize
The size of the EntityBase.
int mScreenNumber
The screen the EntityBase should be drawn to.
bool mIsVisible
The EntityBase is visible on the screen if this is true.
The EntityBase is NOT visible on the screen if this is false.
.
bool mIsSolid
The EntityBase is solid on the screen if this is true.
The EntityBase is NOT solid on the screen if this is false.
.
bool mShouldDestroyed
The EntityBase should be destroyed if this is true.
The EntityBase should NOT be destroyed if this is false.
.
Static Protected Attributes
static uint_least64_t nextId = 0
The first id which is free to use for a new EntityBase object.
Static Private Member Functions
static void increaseNextId ()
Increases the nextId by one.
Detailed Description
This is a general class for every entity in the game world.
This class should be used as a parent class for every entity in the world. Some of the methods must be overridden by the derived classes.
Definition at line 18 of file EntityBase.hpp.
Constructor & Destructor Documentation
EntityBase()
EntityBase::EntityBase (const sf::Vector2f & position, const sf::Vector2f size, int screenNumber, bool isSolid = true, bool isVisible = true)
This is the constructor for the EntityBase class.
Parameters
position The position where the EntityBase should spawn.
size The size of the EntityBase.
screenNumber The screenNumber where the EntityBase should be drawn to.
isSolid Whether or not the EntityBase should be solid or not.
isVisible Whether or not the EntityBase should be drawn to the screen.
Definition at line 10 of file EntityBase.cpp.
References increaseNextId().
~EntityBase()
EntityBase::~EntityBase () virtual
Definition at line 28 of file EntityBase.cpp.
Member Function Documentation
backToStartId()
void EntityBase::backToStartId () static
Set the nextId to zero. (Reset)
This should be called when all EntityBase objects are destroyed.
Definition at line 34 of file EntityBase.cpp.
References nextId.
destroy()
void EntityBase::destroy ()
This method sets mShouldDestroy to true.
mShouldDestroy should be used to check if a EntityBase should be destroyed. So the object can be destroyed outside this class.
Definition at line 101 of file EntityBase.cpp.
References mShouldDestroyed.
draw() [1/2]
virtual void EntityBase::draw (sf::RenderWindow & window) pure virtual
This pure virtual method draws the EntityBase to the sf::RenderWindow.
Parameters
window The window you want to draw to.
Implemented in Character, LevelObject, and Text.
draw() [2/2]
virtual void EntityBase::draw (ViewManager & window) pure virtual
This pure virtual method draws to the sf::RenderWindow.
You should select the correct screen before drawing using ViewManager.
Parameters
window The window you want to draw to.
Implemented in Character, LevelObject, and Text.
drawIfVisible() [1/2]
void EntityBase::drawIfVisible (sf::RenderWindow & window)
This method draws to the sf::RenderWindow if mIsVisible is true.
Parameters
window The window you want to draw to.
Definition at line 151 of file EntityBase.cpp.
References draw(), and mIsVisible.
drawIfVisible() [2/2]
void EntityBase::drawIfVisible (ViewManager & window)
This method draws to the ViewManager if mIsVisible is true.
Parameters
window The window you want to draw to.
Definition at line 157 of file EntityBase.cpp.
References draw(), and mIsVisible.
getGlobalBounds()
sf::FloatRect EntityBase::getGlobalBounds () const virtual
This method returns the global bounds of the EntityBase.
Returns
A sf::Vector2f containing the global bounds of the EntityBase.
Reimplemented in Character, LevelObject, EventTriggeredObject, Text, and Spikes.
Definition at line 73 of file EntityBase.cpp.
References mPosition, and mSize.
getId()
uint_least64_t EntityBase::getId () const
A method to get the id.
Returns
An uint_least64_t containing the id of the EntityBase.
Definition at line 30 of file EntityBase.cpp.
References id.
getNextPosition()
sf::Vector2f EntityBase::getNextPosition () const virtual
This method returns the next position the EntityBase will be.
Note that in the derived classes the nextPosition could be different.
Returns
A sf::Vector2f containing the value of mPosition.
Reimplemented in MoveablePlatform.
Definition at line 65 of file EntityBase.cpp.
References mPosition.
getPosition()
sf::Vector2f EntityBase::getPosition () const virtual
This method returns the value of mPosition.
Returns
A sf::Vector2f containing the value of mPosition.
Reimplemented in LevelObject.
Definition at line 61 of file EntityBase.cpp.
References mPosition.
getScreenNumber()
int EntityBase::getScreenNumber () const
This method returns the value of mScreenNumber.
Returns
An int containing the value of mScreenNumber.
Definition at line 81 of file EntityBase.cpp.
References mScreenNumber.
getSize()
sf::Vector2f EntityBase::getSize () const virtual
This method returns the value of mSize.
Returns
A sf::Vector2f containing the value of mSize.
Reimplemented in Character.
Definition at line 69 of file EntityBase.cpp.
References mSize.
handleCollision()
virtual void EntityBase::handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) inline virtual
Function used to handle collisions.
This method is most of the time overridden in derived classes to get the correct behaviour.
Parameters
top This contains all the objects that the Character collides with on the top.
bottom This contains all the objects that the Character collides with on the bottom.
left This contains all the objects that the Character collides with on the left.
right This contains all the objects that the Character collides with on the right.
hitSides This contains booleans of all sides which are true when something collided on that side.
Reimplemented in Character, Player, NPC, MoveablePlatform, Spikes, Projectile, EventTriggeredObject, and Platform.
Definition at line 237 of file EntityBase.hpp.
handleNoCollision()
virtual void EntityBase::handleNoCollision () inline virtual
This function is called when no collision is detected.
This method is most of the time overridden in derived classes to get the correct behaviour.
Reimplemented in Character, NPC, MoveablePlatform, and EventTriggeredObject.
Definition at line 250 of file EntityBase.hpp.
hurt()
virtual void EntityBase::hurt (uint_least8_t damage) inline virtual
This is a virtual method should be overridden if you want to hurt a EntityBase on damage.
Reimplemented in Player, and NPC.
Definition at line 160 of file EntityBase.hpp.
increaseNextId()
void EntityBase::increaseNextId () static private
Increases the nextId by one.
Definition at line 6 of file EntityBase.cpp.
References nextId.
isFinished()
bool EntityBase::isFinished () const virtual
This method is used to check if the EntityBase is finished.
Returns
A bool containing whether the EntityBase is finshed or not.
Reimplemented in Character.
Definition at line 109 of file EntityBase.cpp.
isSolid()
bool EntityBase::isSolid () const
This method returns the value of mIsSolid.
Returns
A bool containing the value of mIsSolid.
Definition at line 97 of file EntityBase.cpp.
References mIsSolid.
isVisible()
bool EntityBase::isVisible () const
This method returns mScreenNumber.
Returns
A bool containing the value of mIsVisible.
Definition at line 89 of file EntityBase.cpp.
References mIsVisible.
move() [1/2]
void EntityBase::move (float deltaX, float deltaY)
This method moves the EntityBase by adding the delta to mPosition.
Parameters
deltaX The amount of X you want to add to mPosition.
deltaY The amount of Y you want to add to mPosition.
Definition at line 38 of file EntityBase.cpp.
References mPosition.
move() [2/2]
void EntityBase::move (const sf::Vector2f & deltaPosition)
This method moves the EntityBase by adding the delta to mPosition.
Parameters
deltaPosition The difference in position you want to add to mPosition.
Definition at line 43 of file EntityBase.cpp.
References mPosition.
removeNonSolid()
void EntityBase::removeNonSolid (std::vector< std::unique_ptr< EntityBase > *> & top, std::vector< std::unique_ptr< EntityBase > *> & bottom, std::vector< std::unique_ptr< EntityBase > *> & left, std::vector< std::unique_ptr< EntityBase > *> & right, CollisionSides & hitSides) const
This method removes the non solid objects from the vector.
Parameters
top This contains all the objects that the Character collides with on the top.
bottom This contains all the objects that the Character collides with on the bottom.
left This contains all the objects that the Character collides with on the left.
right This contains all the objects that the Character collides with on the right.
hitSides This contains booleans of all sides which are true when something collided on that side.
Definition at line 113 of file EntityBase.cpp.
References CollisionSides::bottom, CollisionSides::left, CollisionSides::right, and CollisionSides::top.
setColor()
virtual void EntityBase::setColor (const sf::Color & newColor) inline virtual
This method handles changing color if overridden.
Reimplemented in Text.
Definition at line 276 of file EntityBase.hpp.
setIsSolid()
void EntityBase::setIsSolid (bool isSolid)
This method sets mIsSolid.
Parameters
isSolid The value you want to set mIsSolid to.
Definition at line 93 of file EntityBase.cpp.
References isSolid(), and mIsSolid.
setIsVisible()
void EntityBase::setIsVisible (bool isVisible)
This method sets mIsVisible.
Parameters
isVisible The value you want to set mIsVisible to.
Definition at line 85 of file EntityBase.cpp.
References isVisible(), and mIsVisible.
setPosition() [1/2]
void EntityBase::setPosition (float x, float y)
This method sets mPosition.
Parameters
x The value you want to set mPosition.x to.
y The value you want to set mPosition.y to.
Definition at line 47 of file EntityBase.cpp.
References mPosition.
setPosition() [2/2]
void EntityBase::setPosition (const sf::Vector2f & newPosition) virtual
This method sets mPosition.
Parameters
newPosition The value you want to set mPosition to.
Reimplemented in LevelObject.
Definition at line 52 of file EntityBase.cpp.
References mPosition.
setScreenNumber()
void EntityBase::setScreenNumber (int newScreenNumber)
This method sets the screenNumber.
Parameters
newScreenNumber The value you want to set screenNumber to.
Definition at line 77 of file EntityBase.cpp.
References mScreenNumber.
setSize()
void EntityBase::setSize (const sf::Vector2f & newSize)
This method sets mSize.
Parameters
newSize The value you want to set mSize to.
Definition at line 56 of file EntityBase.cpp.
References mSize.
shouldDestroy()
bool EntityBase::shouldDestroy () const
This method returns mIsSolid.
Returns
A bool containing the value of mIsSolid.
Definition at line 105 of file EntityBase.cpp.
References mShouldDestroyed.
update()
virtual void EntityBase::update (const sf::Time & deltaTime) pure virtual
A pure virtual method used to update the EntityBase.
Parameters
deltaTime The time between the last update and this update. Used to make movement based on time not framerate.
Implemented in Character, NPC, LevelObject, MoveablePlatform, Spikes, Projectile, and Text.
Member Data Documentation
id
uint_least64_t EntityBase::id protected
The id of the EntityBase.
Definition at line 31 of file EntityBase.hpp.
mIsSolid
bool EntityBase::mIsSolid protected
The EntityBase is solid on the screen if this is true.
The EntityBase is NOT solid on the screen if this is false.
.
Definition at line 53 of file EntityBase.hpp.
mIsVisible
bool EntityBase::mIsVisible protected
The EntityBase is visible on the screen if this is true.
The EntityBase is NOT visible on the screen if this is false.
.
Definition at line 48 of file EntityBase.hpp.
mPosition
sf::Vector2f EntityBase::mPosition protected
The position of the EntityBase in the world.
Definition at line 35 of file EntityBase.hpp.
mScreenNumber
int EntityBase::mScreenNumber protected
The screen the EntityBase should be drawn to.
Definition at line 43 of file EntityBase.hpp.
mShouldDestroyed
bool EntityBase::mShouldDestroyed protected
The EntityBase should be destroyed if this is true.
The EntityBase should NOT be destroyed if this is false.
.
Definition at line 58 of file EntityBase.hpp.
mSize
sf::Vector2f EntityBase::mSize protected
The size of the EntityBase.
Definition at line 39 of file EntityBase.hpp.
nextId
uint_least64_t EntityBase::nextId = 0 static protected
The first id which is free to use for a new EntityBase object.
Definition at line 27 of file EntityBase.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Entity/EntityBase.hpp
C:/test/V2C_V2THGA_2018/src/Entity/EntityBase.cpp