V2THGA group 1 (MiNd_F*cK): Player Class Reference
Player Class Reference
This is the Player class.
#include <Player.hpp>
Public Member Functions
Player (const sf::Vector2f &position, int screenNumber)
This is the constructor for the Player class.
virtual ~Player ()
virtual bool shoot () override
This method is used to shoot a lightning bolt.
virtual void hurt (uint_least8_t damage) override
This method hurts the player and display this to the screen.
virtual void bindActions () override
This method binds all the key pressed to the correct actions.
virtual void bindAnimations () override
This method binds the animations to the Character states.
virtual void handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides)
This method handles the collision for the Player.
Public Member Functions inherited from Character
Character (const sf::Vector2f &position, const sf::Vector2f &size, int screenNumber, const sf::Vector2f &maxVelocity, const sf::Vector2f &acceleration, const std::string &characterSheetPath)
This is the constructor of the Character class.
virtual ~Character () override
void addAction (const Action &newAction)
This method adds a new action to mUnperformedActions.
void bindAction (const EventManager &event)
This method binds an event to an action.
void bindAnimation (const State &state, const AnimationSequence &animationSequence)
This method binds a state to an AnimationSequence.
void move (sf::Vector2f &delta)
This method moves the Character.
void applyMovement (const Action &direction)
This method is used to apply the right movement given an action using the velocity.
void updateFacingDirection ()
This method updates the facing direction.
void updateVelocity (const sf::Vector2f &deltaVelocity)
This method adds a given delta velocity to the current mVelocity.
void resetVelocityY ()
This method sets the Y direction of mVelocity to 0.
void resetVelocityX ()
This method sets the X direction of mVelocity to 0.
bool isMovingX () const
This method checks whether the Character is moving in the X direction.
void updateState (const Action &action)
This function updates the current state of the Character.
void startHurtAnimation ()
This method starts the hurting animation.
void animate (const sf::Time &deltaTime)
This method is used to animate the Character his movement.
void left ()
This method moves the Character to the left using applyMovement.
void right ()
This method moves the Character to the right using applyMovement.
void jump ()
This method makes the Character jump into the air.
void run ()
This method makes the Character run using applyMovement.
virtual bool isShooting () const
This method returns the value of mIsShooting.
std::optional< std::unique_ptr< EntityBase > > getProjectile ()
This method returns a projectile when the Character is shooting.
void performAction (const Action &unperformedAction)
This method performs the given action.
virtual sf::Vector2f getSize () const override
This method returns the size of the Character.
virtual sf::FloatRect getGlobalBounds () const override
This method returns the global bounds of the Character.
void setSpriteScale (float x, float y)
This method sets the scale of mSprite and updates mSize accordingly.
void updateSizeUsingSprite ()
This method updates mSize using the global bounds of mSprite.
virtual bool isFinished () const override
This method returns the value of mIsFinished.
virtual void handleNoCollision () override
This method handles a no collision.
virtual void update (const sf::Time &deltaTime) override
This method updates all the values in the Character.
virtual void draw (sf::RenderWindow &window) override
This method draws the Character to a sf::RenderWindow.
virtual void draw (ViewManager &window) override
This method draws the Character to a ViewManager.
Public Member Functions inherited from EntityBase
EntityBase (const sf::Vector2f &position, const sf::Vector2f size, int screenNumber, bool isSolid=true, bool isVisible=true)
This is the constructor for the EntityBase class.
virtual ~EntityBase ()
uint_least64_t getId () const
A method to get the id.
void move (float deltaX, float deltaY)
This method moves the EntityBase by adding the delta to mPosition.
void move (const sf::Vector2f &deltaPosition)
This method moves the EntityBase by adding the delta to mPosition.
void setScreenNumber (int newScreenNumber)
This method sets the screenNumber.
int getScreenNumber () const
This method returns the value of mScreenNumber.
void setIsVisible (bool isVisible)
This method sets mIsVisible.
bool isVisible () const
This method returns mScreenNumber.
void setIsSolid (bool isSolid)
This method sets mIsSolid.
bool isSolid () const
This method returns the value of mIsSolid.
void destroy ()
This method sets mShouldDestroy to true.
bool shouldDestroy () const
This method returns mIsSolid.
void setPosition (float x, float y)
This method sets mPosition.
virtual void setPosition (const sf::Vector2f &newPosition)
This method sets mPosition.
void setSize (const sf::Vector2f &newSize)
This method sets mSize.
virtual sf::Vector2f getPosition () const
This method returns the value of mPosition.
virtual sf::Vector2f getNextPosition () const
This method returns the next position the EntityBase will be.
void removeNonSolid (std::vector< std::unique_ptr< EntityBase > *> &top, std::vector< std::unique_ptr< EntityBase > *> &bottom, std::vector< std::unique_ptr< EntityBase > *> &left, std::vector< std::unique_ptr< EntityBase > *> &right, CollisionSides &hitSides) const
This method removes the non solid objects from the vector.
virtual void setColor (const sf::Color &newColor)
This method handles changing color if overridden.
void drawIfVisible (sf::RenderWindow &window)
This method draws to the sf::RenderWindow if mIsVisible is true.
void drawIfVisible (ViewManager &window)
This method draws to the ViewManager if mIsVisible is true.
Static Public Member Functions
static uint_least8_t getHealth ()
Returns the current health.
static void setMaxHealth (uint_least8_t newMaxHealth)
Sets the maxHealth to the value of newMaxHealth.
static void setHealth (uint_least8_t newHealth)
Sets the health to the value of newhealth.
static void addHealth (int_least8_t deltaHealth)
Adds the deltaHealth to the value of health.
static void resetHealth ()
Sets the health back to the maxHealth.
static uint_least8_t getEnergy ()
Returns the current health.
static void setMaxEnergy (uint_least8_t newMaxEnergy)
Sets the maxEnergy to the value of newMaxEnergy.
static void setEnergy (uint_least8_t newEnergy)
Sets the energy to the value of newEnergy.
static void addEnergy (int_least8_t deltaEnergy)
Adds the deltaEnergy to the value of energy.
static void resetEnergy ()
Sets the health back to the maxHealth.
static void reset ()
Resets both the health and energy.
static bool isDead ()
Returns if the player's health is 0.
static bool isAlive ()
Returns if the player's health is greater than 0.
Static Public Member Functions inherited from EntityBase
static void backToStartId ()
Set the nextId to zero. (Reset)
Static Protected Attributes
static uint_least8_t maxHealth = 10
The maximum health the player is able to have.
static uint_least8_t health = maxHealth
The current health the player has.
static uint_least8_t maxEnergy = 10
The maximum energy the player is able to have.
static uint_least8_t energy = maxEnergy
The current energy the player has.
Static Protected Attributes inherited from EntityBase
static uint_least64_t nextId = 0
The first id which is free to use for a new EntityBase object.
Private Attributes
SoundPlayer mSoundPlayer
Additional Inherited Members
Public Types inherited from Character
enum State {
State::Idle, State::Moving, State::Running, State::Jumping,
State::Falling, State::Shooting
}
enum Action {
Action::Left, Action::Right, Action::Jump, Action::Run,
Action::Shoot, Action::None
}
The actions which a Character is able to perform.
Protected Attributes inherited from Character
uint_least64_t id
The id of a Character used to identify which Character it is.
sf::Vector2f mVelocity
The current velocity of the Character used to move the Character.
sf::Vector2f mMaxVelocity
The mamixum velocity of the Character. The Character is not able to exceed this velocity.
sf::Vector2f mAcceleration
The amount of acceleration of the Character.
bool mIsFacingRight
The Character is facing right if this is true.
The Character is facing left if this is false.
bool mIsInAir
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mIsJumping
The Character is in the air if this is true.
The Character is on the ground if this is false.
bool mCanDoubleJump
The Character is in the air if this is true.
The Character is not on the ground if this is false.
bool mIsRunning
The Character is running if this is true.
The Character is not running if this is false.
bool mIsShooting
The Character is shooting if this is true.
The Character is not shooting if this is false.
bool mIsFinished
The Character is finished if this is true.
The Character is not finished if this is false.
State mPreviousState
The previous state the Character was in.
State mState
The current state the character is in.
sf::Texture mTexture
The texture of the Character.
sf::Sprite mSprite
The sprite of the Character.
bool mIsHurting = false
The Character is hurting if this is true.
The Character is not hurting if this is false.
CollisionSides mRestrictedSides
The direction in which the character can not walk.
float mGravity = 0.0f
The amount of pixels the character moves down each update.
This only occurs if the character is in air.
float mStartingJumpForce = -7.0f
The amount of pixels the character moves up when the jump starts.
float mJumpForce = mStartingJumpForce
The amount of pixels the character moves up each update.
This only occurs if the character is jumping.
float mMaxGravity = 7.0f
The maximum amount of pixels the character moves down each update.
float mJumpAcceleration = 0.3f
The amount of pixels the mJumpForce is decreased by each update.
float mGravityAcceleration = 0.3f
The amount of pixels the mGravity is increased by each update.
Timer mShootTimer
The timer to stop the Character from shooting continuously.
sf::Time mTimeBetweenShots = sf::seconds(1)
The time there is between shots.
sf::Time mTimeSinceLastAnimation
The last time a new picture has been set during a AnimationSequence.
Timer mHurtTimer
The timer used to check if the hurt animation should stop.
sf::Time mTotalHurtTime = sf::seconds(1)
The time the hurt animation is shown.
std::queue< Action > mUnperformedActions = {}
All the unperformed actions. These will be performed in the update method.
sf::Vector2i currentSprite = sf::Vector2i(0,0)
The current location in the spritesheet.
std::vector< std::pair< Action, std::function< void()> > > mActions
These are all the possible actions which can be performed.
std::vector< std::pair< State, AnimationSequence > > mAnimations = {}
These are all the states which should be filled in any derived class.
std::vector< EventManager > actions = {}
These are all the events/actions the Character has.
Protected Attributes inherited from EntityBase
uint_least64_t id
The id of the EntityBase.
sf::Vector2f mPosition
The position of the EntityBase in the world.
sf::Vector2f mSize
The size of the EntityBase.
int mScreenNumber
The screen the EntityBase should be drawn to.
bool mIsVisible
The EntityBase is visible on the screen if this is true.
The EntityBase is NOT visible on the screen if this is false.
.
bool mIsSolid
The EntityBase is solid on the screen if this is true.
The EntityBase is NOT solid on the screen if this is false.
.
bool mShouldDestroyed
The EntityBase should be destroyed if this is true.
The EntityBase should NOT be destroyed if this is false.
.
Detailed Description
This is the Player class.
This class is used to make playable characters for a game. These playable characters move through the levels using the user's input.
Definition at line 12 of file Player.hpp.
Constructor & Destructor Documentation
Player()
Player::Player (const sf::Vector2f & position, int screenNumber)
This is the constructor for the Player class.
Definition at line 90 of file Player.cpp.
References bindActions(), bindAnimations(), and Character::setSpriteScale().
~Player()
Player::~Player () virtual
Definition at line 102 of file Player.cpp.
Member Function Documentation
addEnergy()
void Player::addEnergy (int_least8_t deltaEnergy) static
Adds the deltaEnergy to the value of energy.
Parameters
deltaEnergy The energy value you want to add to energy.
Definition at line 63 of file Player.cpp.
References energy, and maxEnergy.
addHealth()
void Player::addHealth (int_least8_t deltaHealth) static
Adds the deltaHealth to the value of health.
Parameters
deltaHealth The health value you want to add to health.
Definition at line 31 of file Player.cpp.
References health, and maxHealth.
bindActions()
void Player::bindActions () override virtual
This method binds all the key pressed to the correct actions.
This binds all the keys to the right actions in the Character class using the bindAction method. This method should be called while initializing.
Reimplemented from Character.
Definition at line 122 of file Player.cpp.
References Character::addAction(), Character::bindAction(), Character::Jump, Character::Left, Character::Right, Character::Run, and Character::Shoot.
bindAnimations()
void Player::bindAnimations () override virtual
This method binds the animations to the Character states.
The Player animations will be bind using the Character bindAnimation method. This method should be called while initializing.
Reimplemented from Character.
Definition at line 136 of file Player.cpp.
References Character::bindAnimation(), Character::Falling, Character::Idle, Character::Jumping, Character::Moving, and Character::Running.
getEnergy()
uint_least8_t Player::getEnergy () static
Returns the current health.
Returns
A uint_least8_t containing the current health.
Definition at line 45 of file Player.cpp.
References energy.
getHealth()
uint_least8_t Player::getHealth () static
Returns the current health.
Returns
A uint_least8_t containing the current health.
Definition at line 13 of file Player.cpp.
References health.
handleCollision()
void Player::handleCollision (std::vector< std::unique_ptr< EntityBase > *> top, std::vector< std::unique_ptr< EntityBase > *> bottom, std::vector< std::unique_ptr< EntityBase > *> left, std::vector< std::unique_ptr< EntityBase > *> right, CollisionSides hitSides) virtual
This method handles the collision for the Player.
In this method there will be checked if the finished is reached. All the other collision handeling in doen inside the Character class.
Reimplemented from Character.
Definition at line 184 of file Player.cpp.
References Character::handleCollision(), Character::left(), Character::mIsFinished, and Character::right().
hurt()
void Player::hurt (uint_least8_t damage) override virtual
This method hurts the player and display this to the screen.
The character startHurtAnimation is called to make de Player look like it's getting hurt
Parameters
damage The amount of damage the Player took.
Reimplemented from EntityBase.
Definition at line 112 of file Player.cpp.
References health, Sounds::hurt, mSoundPlayer, SoundPlayer::play(), and Character::startHurtAnimation().
isAlive()
bool Player::isAlive () static
Returns if the player's health is greater than 0.
Definition at line 86 of file Player.cpp.
References health.
isDead()
bool Player::isDead () static
Returns if the player's health is 0.
Definition at line 82 of file Player.cpp.
References isAlive().
reset()
void Player::reset () static
Resets both the health and energy.
Definition at line 77 of file Player.cpp.
References resetEnergy(), and resetHealth().
resetEnergy()
void Player::resetEnergy () static
Sets the health back to the maxHealth.
Definition at line 73 of file Player.cpp.
References energy, and maxEnergy.
resetHealth()
void Player::resetHealth () static
Sets the health back to the maxHealth.
Definition at line 41 of file Player.cpp.
References health, and maxHealth.
setEnergy()
void Player::setEnergy (uint_least8_t newEnergy) static
Sets the energy to the value of newEnergy.
Parameters
newEnergy The energy value you want to set in energy.
Definition at line 53 of file Player.cpp.
References energy, and maxEnergy.
setHealth()
void Player::setHealth (uint_least8_t newHealth) static
Sets the health to the value of newhealth.
Parameters
newHealth The health value you want to set in health.
Definition at line 21 of file Player.cpp.
References health, and maxHealth.
setMaxEnergy()
void Player::setMaxEnergy (uint_least8_t newMaxEnergy) static
Sets the maxEnergy to the value of newMaxEnergy.
Parameters
newMaxEnergy The energy maxEnergy will be set to.
Definition at line 49 of file Player.cpp.
References maxEnergy.
setMaxHealth()
void Player::setMaxHealth (uint_least8_t newMaxHealth) static
Sets the maxHealth to the value of newMaxHealth.
Parameters
newMaxHealth The health maxHealth will be set to.
Definition at line 17 of file Player.cpp.
References maxHealth.
shoot()
bool Player::shoot () override virtual
This method is used to shoot a lightning bolt.
In this method the Character::shoot is called to start shooting the bolt. In this class the energy will be decreased.
Returns
A bool containing whether or not the player was able to shoot.
Reimplemented from Character.
Definition at line 104 of file Player.cpp.
References energy, and Character::shoot().
Member Data Documentation
energy
uint_least8_t Player::energy = maxEnergy static protected
The current energy the player has.
Definition at line 30 of file Player.hpp.
health
uint_least8_t Player::health = maxHealth static protected
The current health the player has.
Definition at line 22 of file Player.hpp.
maxEnergy
uint_least8_t Player::maxEnergy = 10 static protected
The maximum energy the player is able to have.
Definition at line 26 of file Player.hpp.
maxHealth
uint_least8_t Player::maxHealth = 10 static protected
The maximum health the player is able to have.
Definition at line 18 of file Player.hpp.
mSoundPlayer
SoundPlayer Player::mSoundPlayer private
Definition at line 14 of file Player.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Entity/Player.hpp
C:/test/V2C_V2THGA_2018/src/Entity/Player.cpp