V2THGA group 1 (MiNd_F*cK): Collision Class Reference
Collision Class Reference
Class to handle collisionchecking.
#include <Collision.hpp>
Public Member Functions
Collision (ViewManager &viewManager, std::vector< std::unique_ptr< EntityBase >> &staticItems, std::vector< std::unique_ptr< EntityBase >> &dynamicItems)
Constructor for Collision class.
virtual ~Collision ()
void checkCollisions ()
Method to check collisions for all dynamic items.
Private Member Functions
void updateViewInfo ()
This method updates all the view information, such as position and size.
void checkScope ()
This method checks if items are in the view.
bool checkScopeLeftTop (const sf::FloatRect &currentItem, const ViewInfo &currentViewInfo)
This method checks if the left top corner of a object is in view.
bool checkScopeRightTop (const sf::FloatRect &currentItem, const ViewInfo &currentViewInfo)
This method checks if the right top corner of an object is in view.
bool checkScopeLeftBottom (const sf::FloatRect &currentItem, const ViewInfo &currentViewInfo)
This method checks if the left bottom corner of a object is in view.
bool checkScopeRightBottom (const sf::FloatRect &currentItem, const ViewInfo &currentViewInfo)
This method checks if the right bottom corner of a object is in view.
void printViewInfo (ViewInfo info)
Method to print the ViewInfo struct.
void collisionHandler (std::unique_ptr< EntityBase > &object1, std::unique_ptr< EntityBase > &object2, std::vector< std::unique_ptr< EntityBase > *> &top, std::vector< std::unique_ptr< EntityBase > *> &bottom, std::vector< std::unique_ptr< EntityBase > *> &left, std::vector< std::unique_ptr< EntityBase > *> &right, CollisionSides &collisionSides)
This method handles the rest of the collision checking after a collision is found.
void reloadViewInfo ()
Method to reload all the view information.
CollisionBoxes createCollisionBoxes (const sf::FloatRect &mainBox)
Method to create all the collisionBoxes for each side.
Private Attributes
ViewManager & mViewManager
A reference to the viewManager.
std::vector< std::unique_ptr< EntityBase > > & mStaticItems
A reference to the vector with static items.
std::vector< std::unique_ptr< EntityBase > > & mDynamicItems
A reference to the vector with dynamic items.
int mAmountOfScreens
The amount of screens in the window.
std::vector< int > mNeedsCheckStatic
This vector contains the indexes of the static items that need collision checking.
std::vector< int > mNeedsCheckDynamic
This vector contains the indexes of the Dynamic items that need collision checking.
std::vector< ViewInfo > mViewInfos
This vector contains the information of all the views.
Detailed Description
Class to handle collisionchecking.
Definition at line 48 of file Collision.hpp.
Constructor & Destructor Documentation
Collision()
Collision::Collision (ViewManager & viewManager, std::vector< std::unique_ptr< EntityBase >> & staticItems, std::vector< std::unique_ptr< EntityBase >> & dynamicItems)
Constructor for Collision class.
Parameters
viewManager A reference to the viewManager needed for view information such as position and size.
staticItems A reference to the static objects vector.
dynamicItems A reference to the dynamic objects vector.
Definition at line 9 of file Collision.cpp.
References ViewManager::getAmountOfScreens(), ViewManager::getViewPosition(), ViewManager::getViewSize(), mAmountOfScreens, mViewInfos, and mViewManager.
~Collision()
Collision::~Collision () virtual
Definition at line 24 of file Collision.cpp.
Member Function Documentation
checkCollisions()
void Collision::checkCollisions ()
Method to check collisions for all dynamic items.
Definition at line 158 of file Collision.cpp.
References checkScope(), collisionHandler(), mDynamicItems, mNeedsCheckDynamic, mNeedsCheckStatic, and mStaticItems.
checkScope()
void Collision::checkScope () private
This method checks if items are in the view.
If a item is out of view it will not be checked for collisions.
By checking this first a lot of time is saved in further collision checking.
Definition at line 86 of file Collision.cpp.
References checkScopeLeftBottom(), checkScopeLeftTop(), checkScopeRightBottom(), checkScopeRightTop(), mDynamicItems, mNeedsCheckDynamic, mNeedsCheckStatic, mStaticItems, mViewInfos, and updateViewInfo().
checkScopeLeftBottom()
bool Collision::checkScopeLeftBottom (const sf::FloatRect & currentItem, const ViewInfo & currentViewInfo) private
This method checks if the left bottom corner of a object is in view.
Parameters
currentItem The collisionbox of the current item that needs to be checked.
currentViewInfo The information of the view the object is in.
Definition at line 70 of file Collision.cpp.
References ViewInfo::viewPosition, and ViewInfo::viewSize.
checkScopeLeftTop()
bool Collision::checkScopeLeftTop (const sf::FloatRect & currentItem, const ViewInfo & currentViewInfo) private
This method checks if the left top corner of a object is in view.
Parameters
currentItem The collisionBox of the current item that needs to be checked.
currentViewInfo The information of the view the object is in.
Definition at line 55 of file Collision.cpp.
References ViewInfo::viewPosition, and ViewInfo::viewSize.
checkScopeRightBottom()
bool Collision::checkScopeRightBottom (const sf::FloatRect & currentItem, const ViewInfo & currentViewInfo) private
This method checks if the right bottom corner of a object is in view.
Parameters
currentItem The collisionbox of the current item that needs to be checked.
currentViewInfo The information of the view the object is in.
Definition at line 77 of file Collision.cpp.
References ViewInfo::viewPosition, and ViewInfo::viewSize.
checkScopeRightTop()
bool Collision::checkScopeRightTop (const sf::FloatRect & currentItem, const ViewInfo & currentViewInfo) private
This method checks if the right top corner of an object is in view.
Parameters
currentItem The collisionBox of the current item that needs to be checked.
currentViewInfo The information of the view the object is in.
Definition at line 63 of file Collision.cpp.
References ViewInfo::viewPosition, and ViewInfo::viewSize.
collisionHandler()
void Collision::collisionHandler (std::unique_ptr< EntityBase > & object1, std::unique_ptr< EntityBase > & object2, std::vector< std::unique_ptr< EntityBase > *> & top, std::vector< std::unique_ptr< EntityBase > *> & bottom, std::vector< std::unique_ptr< EntityBase > *> & left, std::vector< std::unique_ptr< EntityBase > *> & right, CollisionSides & collisionSides) private
This method handles the rest of the collision checking after a collision is found.
When a collision is found on the main collisionBox this function checks where the collision occured. Possibilities are: Left, Right, Top and Bottom.
After checking which side the collision is detected the object is added to the corresponding vector. The collisionSides struct is updated with a true on the corresponding side.
Parameters
object1 The first object to check the collision width.
object2 The second object to check the collision width.
top Vector with top collisioned objects.
bottom Vector with bottom collisioned objects.
left Vector with left collisioned objects.
right Vector with right collisioned objects.
collisionSides The collisionSides struct
Definition at line 129 of file Collision.cpp.
References CollisionSides::bottom, CollisionBoxes::bottomBox, createCollisionBoxes(), CollisionSides::left, CollisionBoxes::leftBox, CollisionSides::right, CollisionBoxes::rightBox, CollisionSides::top, and CollisionBoxes::topBox.
createCollisionBoxes()
CollisionBoxes Collision::createCollisionBoxes (const sf::FloatRect & mainBox) private
Method to create all the collisionBoxes for each side.
Parameters
mainBox The box on bases of which the other boxes need to be created.
Definition at line 117 of file Collision.cpp.
printViewInfo()
void Collision::printViewInfo (ViewInfo info) private
Method to print the ViewInfo struct.
Parameters
info The info that needs to be printed.
Definition at line 29 of file Collision.cpp.
References ViewInfo::viewNumber, ViewInfo::viewPosition, and ViewInfo::viewSize.
reloadViewInfo()
void Collision::reloadViewInfo () private
Method to reload all the view information.
Definition at line 37 of file Collision.cpp.
References ViewManager::getViewPosition(), ViewManager::getViewSize(), mAmountOfScreens, mViewInfos, and mViewManager.
updateViewInfo()
void Collision::updateViewInfo () private
This method updates all the view information, such as position and size.
Definition at line 45 of file Collision.cpp.
References ViewManager::getAmountOfScreens(), ViewManager::getViewPosition(), mAmountOfScreens, mViewInfos, mViewManager, and reloadViewInfo().
Member Data Documentation
mAmountOfScreens
int Collision::mAmountOfScreens private
The amount of screens in the window.
Definition at line 64 of file Collision.hpp.
mDynamicItems
std::vector<std::unique_ptr<EntityBase> >& Collision::mDynamicItems private
A reference to the vector with dynamic items.
Definition at line 60 of file Collision.hpp.
mNeedsCheckDynamic
std::vector<int> Collision::mNeedsCheckDynamic private
This vector contains the indexes of the Dynamic items that need collision checking.
Definition at line 72 of file Collision.hpp.
mNeedsCheckStatic
std::vector<int> Collision::mNeedsCheckStatic private
This vector contains the indexes of the static items that need collision checking.
Definition at line 68 of file Collision.hpp.
mStaticItems
std::vector<std::unique_ptr<EntityBase> >& Collision::mStaticItems private
A reference to the vector with static items.
Definition at line 56 of file Collision.hpp.
mViewInfos
std::vector<ViewInfo> Collision::mViewInfos private
This vector contains the information of all the views.
Definition at line 76 of file Collision.hpp.
mViewManager
ViewManager& Collision::mViewManager private
A reference to the viewManager.
Definition at line 52 of file Collision.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/Entity/Collision.hpp
C:/test/V2C_V2THGA_2018/src/Entity/Collision.cpp