V2THGA group 1 (MiNd_F*cK): GameManager Class Reference
GameManager Class Reference
Main game class that manages every aspect of the game.
#include <GameManager.hpp>
Public Member Functions
GameManager (const std::string &levelFileName)
Constructor for GameManager class.
virtual ~GameManager ()
void runGame ()
Function to start the game.
Private Member Functions
void dynamicItemsErase (unsigned int index)
Delete a object from dynamicItems.
bool readLevelFileNames (const std::string &levelFileName)
Function to read all the levelfile names form a all file.
void readLevelInfo ()
Function to read all the level information using the factory.
void applyLevelSettings ()
Function to apply all the settings.
void createLevel ()
Function to create a level.
void createBackgrounds ()
Function to create all the backgrounds.
void moveScreens ()
Function to move the screens according to player position.
void findPlayerIndexes ()
Function to search where the players are in the mDynamic items.
void selectScreen (int screenNumber)
Function to select a screen.
void clearLevel ()
Function to clear all the level information.
bool checkPlayerOutView ()
Funcion te check if a player falls beyond the maximum size of a level.
bool checkLevelFinished ()
Function to check if the level is Finished.
bool checkLosingConditions ()
Function to check if the player is death.
bool check2Selected ()
Function te check if player selecter 2 or more screens.
void gotoNextLevel ()
Function to go to the next level.
void gotoPreviousLevel ()
Function to go to the previous level.
void respawn ()
Function to respawn (restart a level while keeping death count)
Private Attributes
int mCurrentLevel
The current Level that is playing.
int mCurrentDeathCount = 0
The current amount of deaths.
int mCurrentScreensNotFinished
How many of the screens are finished already.
bool mPlayingLevel = false
Is there currently a level playing.
bool mPlayerRespawn = false
Is the player currently respawning.
sf::RenderWindow mMainWindow
The main RenderWindow for the game.
ViewManager mViewManager
The ViewManager needed to draw to mulitple screens see ViewManager doucmentation for more info.
Factory mFactory
The factory needed to read all the level information.
HUD mHUD
The HUD that displays the healt/energy and death.
SoundPlayer mSoundPlayer
Collision mCollisionManager
SettingsData mCurrentSettings
The struct that contains the settings for the current level.
sf::Music mMusic
The game music.
sf::Clock mUpdateClock
Clock used for deltaTime.
sf::Time mPassedTime
Time Passed between updates.
const sf::Time mFrameTime = sf::milliseconds(10)
Time between each frame.
std::vector< std::unique_ptr< EntityBase > > mStaticItems = {}
Vector with all the static game objects such as platforms.
std::vector< std::unique_ptr< EntityBase > > mDynamicItems = {}
Vector with all the static game objects such as movable platforms and players.
std::vector< std::unique_ptr< EntityBase > > mBackgrounds = {}
Vector with all the backgrounds.
std::vector< std::unique_ptr< EntityBase > > mFinishTexts = {}
Vector with all the Finish texts.
std::vector< std::string > mLevelFileNames
Vector with all the names of the level files.
std::string mPathLevels = "../res/levels/"
Path to all the level files.
std::string mPathBackgrounds = "../res/Textures/Background/"
Path to all the backgrounds.
std::string mPathFinish = "../res/Textures/Finish/"
Path to all the Finish sprites.
std::string mPathOverlay = "../res/Textures/Overlay/"
Path to all the overlay sprites.
std::string mPathMusic = "../res/Sounds/Music/"
Path to all the music files.
std::vector< int > mPlayerIndexes = {}
Vector with the indexes of the players in the mDynamicItems.
std::array< bool, 4 > mSelectedScreen = { false,false,false,false }
Array to see which screens are selected.
std::array< bool, 4 > mFinishedScreen = { false,false,false,false }
Array to see which screens are finished.
EventManager actions [8]
Array of actions.
Detailed Description
Main game class that manages every aspect of the game.
Definition at line 23 of file GameManager.hpp.
Constructor & Destructor Documentation
GameManager()
GameManager::GameManager (const std::string & levelFileName)
Constructor for GameManager class.
This constructor constructs a GameManager using the given txt file.
Parameters
levelFileName This parameter contains the file name of the all text file.
Definition at line 7 of file GameManager.cpp.
References readLevelFileNames().
~GameManager()
GameManager::~GameManager () virtual
Definition at line 20 of file GameManager.cpp.
Member Function Documentation
applyLevelSettings()
void GameManager::applyLevelSettings () private
Function to apply all the settings.
Applies settings such as amount of screens and resets the Health.
Definition at line 65 of file GameManager.cpp.
References ViewManager::changeAmountOfScreens(), SettingsData::energy, ViewManager::getAmountOfScreens(), mCurrentScreensNotFinished, mCurrentSettings, mSelectedScreen, mViewManager, SettingsData::noOfScreens, Player::reset(), and Player::setEnergy().
check2Selected()
bool GameManager::check2Selected () private
Function te check if player selecter 2 or more screens.
This function checks if 2 screens or more are selected.
If there is only one or 2 screen(s) both are selected.
Returns
Returns true if contions are met.
Definition at line 242 of file GameManager.cpp.
References mCurrentScreensNotFinished, and mSelectedScreen.
checkLevelFinished()
bool GameManager::checkLevelFinished () private
Function to check if the level is Finished.
Checks if all the finishpoints are reached.
Returns
Returns true if level is finished.
Definition at line 178 of file GameManager.cpp.
References ViewManager::display(), ViewManager::getViewPosition(), ViewManager::getViewSize(), mCurrentLevel, mCurrentScreensNotFinished, mCurrentSettings, mDynamicItems, mFinishedScreen, mFinishTexts, mLevelFileNames, mPathOverlay, mPlayerIndexes, mSelectedScreen, mStaticItems, mViewManager, and SettingsData::noOfScreens.
checkLosingConditions()
bool GameManager::checkLosingConditions () private
Function to check if the player is death.
Returns
Returns true if player lost.
Definition at line 159 of file GameManager.cpp.
References checkPlayerOutView(), and Player::isDead().
checkPlayerOutView()
bool GameManager::checkPlayerOutView () private
Funcion te check if a player falls beyond the maximum size of a level.
Returns
returs true if player is out of bounds.
Definition at line 166 of file GameManager.cpp.
References mCurrentSettings, mDynamicItems, mPlayerIndexes, and SettingsData::totalLevelSize.
clearLevel()
void GameManager::clearLevel () private
Function to clear all the level information.
Clears all the level information.
Definition at line 146 of file GameManager.cpp.
References mBackgrounds, mDynamicItems, mFinishedScreen, mFinishTexts, mPlayerIndexes, mSelectedScreen, and mStaticItems.
createBackgrounds()
void GameManager::createBackgrounds () private
Function to create all the backgrounds.
Definition at line 78 of file GameManager.cpp.
References SettingsData::backgroundImages, ViewManager::getViewSize(), mBackgrounds, mCurrentSettings, mPathBackgrounds, mViewManager, and SettingsData::noOfScreens.
createLevel()
void GameManager::createLevel () private
Function to create a level.
Uses other functions such as clearLevel and readLevelInfo.
Definition at line 48 of file GameManager.cpp.
References applyLevelSettings(), clearLevel(), createBackgrounds(), findPlayerIndexes(), and readLevelInfo().
dynamicItemsErase()
void GameManager::dynamicItemsErase (unsigned int index) private
Delete a object from dynamicItems.
Parameters
index The index at which the object needs to be deleted
Definition at line 22 of file GameManager.cpp.
References findPlayerIndexes(), and mDynamicItems.
findPlayerIndexes()
void GameManager::findPlayerIndexes () private
Function to search where the players are in the mDynamic items.
Definition at line 227 of file GameManager.cpp.
References mDynamicItems, and mPlayerIndexes.
gotoNextLevel()
void GameManager::gotoNextLevel () private
Function to go to the next level.
Definition at line 258 of file GameManager.cpp.
References mCurrentLevel, mLevelFileNames, and mPlayingLevel.
gotoPreviousLevel()
void GameManager::gotoPreviousLevel () private
Function to go to the previous level.
Definition at line 267 of file GameManager.cpp.
References mCurrentLevel, and mPlayingLevel.
moveScreens()
void GameManager::moveScreens () private
Function to move the screens according to player position.
Definition at line 92 of file GameManager.cpp.
References ViewManager::getViewPosition(), ViewManager::getViewSize(), mBackgrounds, mCurrentSettings, mDynamicItems, mFinishedScreen, ViewManager::move(), mPlayerIndexes, mViewManager, ViewManager::selectMoveScreen(), and SettingsData::totalLevelSize.
readLevelFileNames()
bool GameManager::readLevelFileNames (const std::string & levelFileName) private
Function to read all the levelfile names form a all file.
Parameters
levelFileName The file Name of the all file.
Returns
Returns false when error has occured.
Definition at line 30 of file GameManager.cpp.
References mLevelFileNames.
readLevelInfo()
void GameManager::readLevelInfo () private
Function to read all the level information using the factory.
Definition at line 57 of file GameManager.cpp.
References mCurrentLevel, mCurrentSettings, mDynamicItems, mFactory, mLevelFileNames, mPathLevels, mStaticItems, and Factory::readLevelFile().
respawn()
void GameManager::respawn () private
Function to respawn (restart a level while keeping death count)
Definition at line 274 of file GameManager.cpp.
References createLevel(), and mPlayerRespawn.
runGame()
void GameManager::runGame ()
Function to start the game.
Definition at line 279 of file GameManager.cpp.
References actions, EntityBase::backToStartId(), check2Selected(), Collision::checkCollisions(), checkLevelFinished(), checkLosingConditions(), ViewManager::clear(), ViewManager::close(), createLevel(), Sounds::death, ViewManager::display(), HUD::draw(), dynamicItemsErase(), Player::getEnergy(), Player::getHealth(), gotoNextLevel(), ViewManager::isOpen(), mBackgrounds, mCollisionManager, mCurrentDeathCount, mCurrentSettings, mDynamicItems, mFinishTexts, mFrameTime, mHUD, mMusic, moveScreens(), mPassedTime, mPathMusic, mPlayerIndexes, mPlayerRespawn, mPlayingLevel, mSelectedScreen, mSoundPlayer, mStaticItems, mUpdateClock, mViewManager, SoundPlayer::play(), ViewManager::pollEvent(), ViewManager::resetBordorColor(), ViewManager::setBordorColor(), SettingsData::songName, HUD::updateDeathCount(), HUD::updateEnergy(), and HUD::updateHealth().
selectScreen()
void GameManager::selectScreen (int screenNumber) private
Function to select a screen.
Parameters
screenNumber The screen you want to select.
Definition at line 236 of file GameManager.cpp.
References mFinishedScreen, and mSelectedScreen.
Member Data Documentation
actions
EventManager GameManager::actions[8] private
Initial value:
= {
        EventManager(sf::Keyboard::Num1,    [&]() {selectScreen(1); }, sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Num2,    [&]() {selectScreen(2); }, sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Num3,    [&]() {selectScreen(3); }, sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Num4,    [&]() {selectScreen(4); }, sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Numpad6, [&]() {gotoNextLevel(); }, sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Numpad4, [&]() {gotoPreviousLevel();},sf::Event::KeyReleased),
        EventManager(sf::Keyboard::BackSpace, [&]() {respawn();},sf::Event::KeyReleased),
        EventManager(sf::Keyboard::Escape,  [&]() {mViewManager.close(); })
    }
Array of actions.
This array contains all the key bindings nessecary.
Numbers 1-4 for selecting screens 1-4.
Escape for closing the game.
nuped6/4 to change level.
backspace to respawn.
Definition at line 242 of file GameManager.hpp.
mBackgrounds
std::vector<std::unique_ptr<EntityBase> > GameManager::mBackgrounds = {} private
Vector with all the backgrounds.
Definition at line 95 of file GameManager.hpp.
mCollisionManager
Collision GameManager::mCollisionManager private
Definition at line 63 of file GameManager.hpp.
mCurrentDeathCount
int GameManager::mCurrentDeathCount = 0 private
The current amount of deaths.
Definition at line 31 of file GameManager.hpp.
mCurrentLevel
int GameManager::mCurrentLevel private
The current Level that is playing.
Definition at line 27 of file GameManager.hpp.
mCurrentScreensNotFinished
int GameManager::mCurrentScreensNotFinished private
How many of the screens are finished already.
Definition at line 35 of file GameManager.hpp.
mCurrentSettings
SettingsData GameManager::mCurrentSettings private
The struct that contains the settings for the current level.
Definition at line 67 of file GameManager.hpp.
mDynamicItems
std::vector<std::unique_ptr<EntityBase> > GameManager::mDynamicItems = {} private
Vector with all the static game objects such as movable platforms and players.
Definition at line 91 of file GameManager.hpp.
mFactory
Factory GameManager::mFactory private
The factory needed to read all the level information.
Definition at line 55 of file GameManager.hpp.
mFinishedScreen
std::array<bool, 4> GameManager::mFinishedScreen = { false,false,false,false } private
Array to see which screens are finished.
Definition at line 135 of file GameManager.hpp.
mFinishTexts
std::vector<std::unique_ptr<EntityBase> > GameManager::mFinishTexts = {} private
Vector with all the Finish texts.
Definition at line 99 of file GameManager.hpp.
mFrameTime
const sf::Time GameManager::mFrameTime = sf::milliseconds(10) private
Time between each frame.
Definition at line 83 of file GameManager.hpp.
mHUD
HUD GameManager::mHUD private
The HUD that displays the healt/energy and death.
Definition at line 59 of file GameManager.hpp.
mLevelFileNames
std::vector<std::string> GameManager::mLevelFileNames private
Vector with all the names of the level files.
Definition at line 103 of file GameManager.hpp.
mMainWindow
sf::RenderWindow GameManager::mMainWindow private
The main RenderWindow for the game.
Definition at line 47 of file GameManager.hpp.
mMusic
sf::Music GameManager::mMusic private
The game music.
Definition at line 71 of file GameManager.hpp.
mPassedTime
sf::Time GameManager::mPassedTime private
Time Passed between updates.
Definition at line 79 of file GameManager.hpp.
mPathBackgrounds
std::string GameManager::mPathBackgrounds = "../res/Textures/Background/" private
Path to all the backgrounds.
Definition at line 111 of file GameManager.hpp.
mPathFinish
std::string GameManager::mPathFinish = "../res/Textures/Finish/" private
Path to all the Finish sprites.
Definition at line 115 of file GameManager.hpp.
mPathLevels
std::string GameManager::mPathLevels = "../res/levels/" private
Path to all the level files.
Definition at line 107 of file GameManager.hpp.
mPathMusic
std::string GameManager::mPathMusic = "../res/Sounds/Music/" private
Path to all the music files.
Definition at line 123 of file GameManager.hpp.
mPathOverlay
std::string GameManager::mPathOverlay = "../res/Textures/Overlay/" private
Path to all the overlay sprites.
Definition at line 119 of file GameManager.hpp.
mPlayerIndexes
std::vector<int> GameManager::mPlayerIndexes = {} private
Vector with the indexes of the players in the mDynamicItems.
Definition at line 127 of file GameManager.hpp.
mPlayerRespawn
bool GameManager::mPlayerRespawn = false private
Is the player currently respawning.
Definition at line 43 of file GameManager.hpp.
mPlayingLevel
bool GameManager::mPlayingLevel = false private
Is there currently a level playing.
Definition at line 39 of file GameManager.hpp.
mSelectedScreen
std::array<bool, 4> GameManager::mSelectedScreen = { false,false,false,false } private
Array to see which screens are selected.
Definition at line 131 of file GameManager.hpp.
mSoundPlayer
SoundPlayer GameManager::mSoundPlayer private
Definition at line 61 of file GameManager.hpp.
mStaticItems
std::vector<std::unique_ptr<EntityBase> > GameManager::mStaticItems = {} private
Vector with all the static game objects such as platforms.
Definition at line 87 of file GameManager.hpp.
mUpdateClock
sf::Clock GameManager::mUpdateClock private
Clock used for deltaTime.
Definition at line 75 of file GameManager.hpp.
mViewManager
ViewManager GameManager::mViewManager private
The ViewManager needed to draw to mulitple screens see ViewManager doucmentation for more info.
Definition at line 51 of file GameManager.hpp.
The documentation for this class was generated from the following files:
C:/test/V2C_V2THGA_2018/src/GameManager.hpp
C:/test/V2C_V2THGA_2018/src/GameManager.cpp